<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class T2026NegrosOrientalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rows = [
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0010',
                'name_of_institution' => 'Cuttin\' Loose Beauty Culture (CLBC) Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Maria Luz- Cole Havranek',
                'address' => 'Room 201 and 203, Bandera Bldg., Cervantes St., Brgy. Poblacion 8, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.301933736,
                'longitude_point' => 123.3040585,
                'tel_no' => '(035)4221944',
                'e_mail_address' => 'clbci.techvoc@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Human Health/ Health Care',
                'course_registered_program' => 'Hilot (Wellness Massage) NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '120 Hours',
                'program_reg_no' => 'WTR No. MTP-202307HHCHIL208-082',
                'date_issued' => '2023-12-11 00:00:00',
                'expiration_date' => '2028-12-12 00:00:00',
                'trainer' => 'Myra A. Umbac
Terence L. Havranek
Stanley Antonio D. Umbac',
                'nttc' => 'TMC No. 20074601000013
TMC No. 18074601000234
TMC No. 19074601000117',
                'expiration_date_of_nttc' => '5/3/2025
10/19/2023
6/7/2024',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0007',
                'name_of_institution' => 'People Skills and Management Institute, Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Ariel D. Ronato - Chairman of the Board',
                'address' => '1F Bandera Bldg., 27 Cervantes St., Dumaguete City, Negros Oriental',
                'latitude_point' => 9.310555416,
                'longitude_point' => 123.3048972,
                'tel_no' => '(035) 420-9600',
                'e_mail_address' => null,
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Information and Communication Technology',
                'course_registered_program' => 'Contact Center Services NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '144 hours',
                'program_reg_no' => 'WTR No. MTP-202307ICTCCS214-088',
                'date_issued' => '2024-01-25 00:00:00',
                'expiration_date' => '2029-01-26 00:00:00',
                'trainer' => 'Lovely Mae F. Glinogo
Liezel Y. Macolbacol
Rolando D. Gadiane, Jr.',
                'nttc' => 'TMC No. 22074601000082
TMC No. 19074601000093
TMC No. 20074601000023',
                'expiration_date_of_nttc' => '6/12/2027
3/28/2024
9/1/2025',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0008',
                'name_of_institution' => 'Foundation University Inc.',
                'formerly_name_of_tvi' => '(Vicente and Sofia Sinco Foundation, Inc.) 
(V.G. Sinco Educational Corporation)',
                'name_of_institution_s_head' => 'Vicente G. Sinco - President',
                'address' => 'Dr. Miciano Raod, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.306198793,
                'longitude_point' => 123.3014725,
                'tel_no' => '(035) 422-9167',
                'e_mail_address' => 'richie.bungart@foundationu.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'HEI',
                'status' => 'WTR-MTP',
                'sector' => 'Tourism',
                'course_registered_program' => 'Bread and Pastry Production NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '141 Hours',
                'program_reg_no' => 'WTR No. MTP-202307TRSBPP209-099',
                'date_issued' => '2024-01-26 00:00:00',
                'expiration_date' => '2029-01-29 00:00:00',
                'trainer' => 'Antonio T. Bendal, Jr.
Jorie May J. Barraquias
Meraflor T. Ventero',
                'nttc' => 'NTTC No. 211707221200170',
                'expiration_date_of_nttc' => '10/03/2026',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0008',
                'name_of_institution' => 'Foundation University Inc.',
                'formerly_name_of_tvi' => '(Vicente and Sofia Sinco Foundation, Inc.) 
(V.G. Sinco Educational Corporation)',
                'name_of_institution_s_head' => 'Vicente G. Sinco - President',
                'address' => 'Dr. Miciano Raod, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.306198793,
                'longitude_point' => 123.3014725,
                'tel_no' => '(035) 422-9167',
                'e_mail_address' => 'richie.bungart@foundationu.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'HEI',
                'status' => 'WTR-MTP',
                'sector' => 'Social, Community Development and Other Services',
                'course_registered_program' => 'Bookkeeping NC III - Mobile Training Program',
                'pgf_level' => 'NC III',
                'duration' => '292 Hours',
                'program_reg_no' => 'WTR No. MTP-202307SOCBKP307-100',
                'date_issued' => '2023-07-07 00:00:00',
                'expiration_date' => '2028-04-21 00:00:00',
                'trainer' => 'Richie B. Bungart',
                'nttc' => 'NTTC No. 232307461300112',
                'expiration_date_of_nttc' => '25/01/2028',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0008',
                'name_of_institution' => 'Foundation University Inc.',
                'formerly_name_of_tvi' => '(Vicente and Sofia Sinco Foundation, Inc.) 
(V.G. Sinco Educational Corporation)',
                'name_of_institution_s_head' => 'Vicente G. Sinco - President',
                'address' => 'Dr. Miciano Raod, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.306198793,
                'longitude_point' => 123.3014725,
                'tel_no' => '(035) 422-9167',
                'e_mail_address' => 'richie.bungart@foundationu.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'HEI',
                'status' => 'WTR-MTP',
                'sector' => 'Tourism',
                'course_registered_program' => 'Cookery NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '316 Hours',
                'program_reg_no' => 'WTR No. MTP-202307TRSCOK214-101',
                'date_issued' => '2024-01-26 00:00:00',
                'expiration_date' => '2029-01-29 00:00:00',
                'trainer' => 'Antonio T. Bendal, Jr.
Jorie May J. Barraquias',
                'nttc' => 'NTTC No. 191907461200367',
                'expiration_date_of_nttc' => '17/07/2024',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0013',
                'name_of_institution' => 'Provincial Training Center - Dumaguete',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Jesila A. Ocariza - Center Administrator',
                'address' => 'Barangay Candau-ay, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.32125056,
                'longitude_point' => 123.2596064,
                'tel_no' => '(035) 422-9481',
                'e_mail_address' => 'ptc.dumaguete@tesda.gov.ph',
                'type_of_institution' => 'Public',
                'classification_of_institution' => 'TTI',
                'status' => 'WTR-MTP',
                'sector' => 'Construction',
                'course_registered_program' => 'Carpentry NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '301 Hours',
                'program_reg_no' => 'WTR No. MTP-202307CONCAR218-108',
                'date_issued' => '2023-07-21 00:00:00',
                'expiration_date' => '2027-09-07 00:00:00',
                'trainer' => 'Elvin Y. Baguio',
                'nttc' => 'NTTC No. 191907461200292',
                'expiration_date_of_nttc' => '13/06/2024',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0031',
                'name_of_institution' => 'Global Tech Manpower Institute Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Eduardo P. Mondarte - Administrator',
                'address' => 'Motong Road Motong, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.317852811,
                'longitude_point' => 123.2891322,
                'tel_no' => '(035) 4210765',
                'e_mail_address' => 'estrelladokhonny@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Metals and Engineering',
                'course_registered_program' => 'Shielded Metal Arc Welding (SMAW) NC I - Mobile Training Program',
                'pgf_level' => 'NC I',
                'duration' => '268 Hours',
                'program_reg_no' => 'WTR No. MTP-202307MEEEAW103-113',
                'date_issued' => '2024-05-31 00:00:00',
                'expiration_date' => '2029-06-01 00:00:00',
                'trainer' => 'Imelda R. Ubag
Eduardo P. Mondarte
Isagani B. Abril
Jungie A. Helardes
Germano A. Jabanes
Edgardo A. Zamora
Josie Wen A. Lejarso
Jimmy L. Oyangorin',
                'nttc' => 'NTTC No. 221707461200070
NTTC No. 221807461200547
NTTC No. 221807461200422
NTTC No. 201907461200300
NTTC No. 221807461200424
NTTC No. 212107461200073
NTTC No. 221807461200453
NTTC No. 232207461200047',
                'expiration_date_of_nttc' => '11/4/2026
10/11/2027
8/4/2027
12/15/2024
3/30/2027
3/4/2024
1/27/2025
1/30/2028',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0031',
                'name_of_institution' => 'Global Tech Manpower Institute Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Eduardo P. Mondarte - Administrator',
                'address' => 'Motong Road Motong, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.317852811,
                'longitude_point' => 123.2891322,
                'tel_no' => '(035) 4210765',
                'e_mail_address' => 'estrelladokhonny@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Metals and Engineering',
                'course_registered_program' => 'Shielded Metal Arc Welding (SMAW) NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '268 Hours',
                'program_reg_no' => 'WTR No. MTP-202307MEEEAW206-114',
                'date_issued' => '2024-05-31 00:00:00',
                'expiration_date' => '2029-06-01 00:00:00',
                'trainer' => 'Imelda R. Ubag
Eduardo P. Mondarte
Isagani B. Abril
Jungie A. Helardes
Germano A. Jabanes
Edgardo A. Zamora
Josie Wen A. Lejarso
Jimmy L. Oyangorin',
                'nttc' => 'NTTC No. 221707461200070
NTTC No. 221807461200547
NTTC No. 221807461200422
NTTC No. 201907461200300
NTTC No. 221807461200424
NTTC No. 212107461200073
NTTC No. 221807461200453
NTTC No. 232207461200047',
                'expiration_date_of_nttc' => '11/4/2026
10/11/2027
8/4/2027
12/15/2024
3/30/2027
3/4/2024
1/27/2025
1/30/2028',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0021',
                'name_of_institution' => 'Teamskills Technological Institute, Inc.',
                'formerly_name_of_tvi' => '"(Formerly:
Teamskills School for Culinary Arts and Hopitality Management, Inc."',
                'name_of_institution_s_head' => 'Ariel D. Ronato, D.B.A. - President/CEO',
                'address' => '3rd Floor, Cecilia Building, Capitol Area, North Road, Daro, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.30910084,
                'longitude_point' => 123.2911675,
                'tel_no' => '(035) 4226159 /
 09175535507 / 09989788731',
                'e_mail_address' => 'info@team-skills.com     
teamskills.acenter@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Tourism',
                'course_registered_program' => 'Bread and Pastry Production NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '141 Hours',
                'program_reg_no' => 'WTR No. MTP-202307TRSBPP209-115',
                'date_issued' => '2024-01-18 00:00:00',
                'expiration_date' => '2029-01-19 00:00:00',
                'trainer' => 'Mishelle S. Chiong
Tina M. Ronato
Ariel D. Ronato
Nancy L. Acabodillo
Crecenciana V. Batalan
Ligaya A. Morales
Alex A. Pagohinog, Jr.
Cira Chel G. Kinkito
Ronalyn G. Turno
Eva A. Quiapo
Chona V. Morales',
                'nttc' => 'NTTC No. 222207461200161
NTTC No. 222207461200163',
                'expiration_date_of_nttc' => '1/26/2027
2/2/2027',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0021',
                'name_of_institution' => 'Teamskills Technological Institute, Inc.',
                'formerly_name_of_tvi' => '"(Formerly:
Teamskills School for Culinary Arts and Hopitality Management, Inc."',
                'name_of_institution_s_head' => 'Ariel D. Ronato, D.B.A. - President/CEO',
                'address' => '3rd Floor, Cecilia Building, Capitol Area, North Road, Daro, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.30910084,
                'longitude_point' => 123.2911675,
                'tel_no' => '(035) 4226159 /
 09175535507 / 09989788731',
                'e_mail_address' => 'info@team-skills.com     
teamskills.acenter@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Tourism',
                'course_registered_program' => 'Cookery NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '316 Hours',
                'program_reg_no' => 'WTR No. MTP-202307TRSCOK214-116',
                'date_issued' => '2024-01-18 00:00:00',
                'expiration_date' => '2029-01-19 00:00:00',
                'trainer' => 'Alex A. Padohinog, Jr.
Mishelle S. Chiong
Ligaya A. Morales
Crecenciana V. Batalan
Nancy L. Acabodillo
 Tina M. Ronato
Ariel D. Ronato
Chona V. Morales
Jonelle Frias',
                'nttc' => 'Not indicated',
                'expiration_date_of_nttc' => 'Not indicated',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0021',
                'name_of_institution' => 'Teamskills Technological Institute, Inc.',
                'formerly_name_of_tvi' => '"(Formerly:
Teamskills School for Culinary Arts and Hopitality Management, Inc."',
                'name_of_institution_s_head' => 'Ariel D. Ronato, D.B.A. - President/CEO',
                'address' => '3rd Floor, Cecilia Building, Capitol Area, North Road, Daro, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.30910084,
                'longitude_point' => 123.2911675,
                'tel_no' => '(035) 4226159 /
 09175535507 / 09989788731',
                'e_mail_address' => 'info@team-skills.com     
teamskills.acenter@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Tourism',
                'course_registered_program' => 'Housekeeping NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '436 Hours',
                'program_reg_no' => 'WTR No. MTP-202307TRSHSK213-117',
                'date_issued' => '2024-01-18 00:00:00',
                'expiration_date' => '2029-01-19 00:00:00',
                'trainer' => 'Estella P. Maraña
Ariel D. Ronato',
                'nttc' => 'NTTC No.: 221707461200009
NTTC No.: 201907461200241',
                'expiration_date_of_nttc' => null,
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0021',
                'name_of_institution' => 'Teamskills Technological Institute, Inc.',
                'formerly_name_of_tvi' => '"(Formerly:
Teamskills School for Culinary Arts and Hopitality Management, Inc."',
                'name_of_institution_s_head' => 'Ariel D. Ronato, D.B.A. - President/CEO',
                'address' => '3rd Floor, Cecilia Building, Capitol Area, North Road, Daro, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.30910084,
                'longitude_point' => 123.2911675,
                'tel_no' => '(035) 4226159 /
 09175535507 / 09989788731',
                'e_mail_address' => 'info@team-skills.com     
teamskills.acenter@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Tourism',
                'course_registered_program' => 'Tourism Promotion Services NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '76 Hours',
                'program_reg_no' => 'WTR NO. MTP-202307TRSTPS215-118',
                'date_issued' => '2024-01-18 00:00:00',
                'expiration_date' => '2029-01-19 00:00:00',
                'trainer' => 'Ariel D. Ronato
Fiona J. Lao',
                'nttc' => 'Not indicated',
                'expiration_date_of_nttc' => 'Not indicated',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0022',
                'name_of_institution' => 'Metro Dumaguete College Inc.',
                'formerly_name_of_tvi' => '(Formerly: FOUR WD COMPUTER TRAINING CENTER, INC.)',
                'name_of_institution_s_head' => 'Dr. Delma P. Manila, DPA, CESO V / President',
                'address' => 'E.J. Blanco Drive Extension, Brgy. Daro, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.31933516,
                'longitude_point' => 123.2912191,
                'tel_no' => '(035) 4229728 / 2259170 / 4226341 / 4224605 / 09177008455',
                'e_mail_address' => 'mdctechvoc@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Electrical and Electronics',
                'course_registered_program' => 'Computer Systems Servicing NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '280 Hours',
                'program_reg_no' => 'WTR No. MTP-202307ELCCSS213-109',
                'date_issued' => '2023-07-25 00:00:00',
                'expiration_date' => '2028-07-25 00:00:00',
                'trainer' => 'Margielen P. Alcoreza
Ricky L. Baldado
Edlyn P. Casal
Lindon A. Damaso
April Joy D. Palahang
Roland R. Palallos',
                'nttc' => 'NTTC No. 202007461200222
NTTC No. 211707461200365
NTTC No. 191807461200313
NTTC No. 201707461200203
NTTC No. 201907461200221
NTTC No. 201707461200162',
                'expiration_date_of_nttc' => '6/24/2025
9/27/2026
6/19/2024
5/21/2025
5/28/202\\5
2/20/2025',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0013',
                'name_of_institution' => 'Provincial Training Center - Dumaguete',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Jesila A. Ocariza - Center Administrator',
                'address' => 'Barangay Candau-ay, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.32125056,
                'longitude_point' => 123.2596064,
                'tel_no' => '(035) 422-9481',
                'e_mail_address' => 'ptc.dumaguete@tesda.gov.ph',
                'type_of_institution' => 'Public',
                'classification_of_institution' => 'TTI',
                'status' => 'WTR-MTP',
                'sector' => 'Automotive and Land Transportation',
                'course_registered_program' => 'Driving NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '118 Hours',
                'program_reg_no' => 'WTR No. MTP-202307ALTDRV204-127',
                'date_issued' => '2024-04-03 00:00:00',
                'expiration_date' => '2029-04-04 00:00:00',
                'trainer' => 'Elvin Y. Baguio
Jerome A. Zamora
Roskie A. Gabutero
Rey Jay E. Jacosalem
Edlyn P. Casal',
                'nttc' => 'NTTC No. 211907461200430
NTTC No. 212007461200057
NTTC No. 211907221200358
NTTC No. 211907461200276
NTTC No. 211807461200321',
                'expiration_date_of_nttc' => '10/19/2026
12/17/2025
09/20/2026
6/09/2026
11/26/2024',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0013',
                'name_of_institution' => 'Provincial Training Center - Dumaguete',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Jesila A. Ocariza - Center Administrator',
                'address' => 'Barangay Candau-ay, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.32125056,
                'longitude_point' => 123.2596064,
                'tel_no' => '(035) 422-9481',
                'e_mail_address' => 'ptc.dumaguete@tesda.gov.ph',
                'type_of_institution' => 'Public',
                'classification_of_institution' => 'TTI',
                'status' => 'WTR-MTP',
                'sector' => 'Construction',
                'course_registered_program' => 'Masonry NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '181 Hours',
                'program_reg_no' => 'WTR No. MTP-202307CONMAS218-128',
                'date_issued' => '2023-08-25 00:00:00',
                'expiration_date' => '2027-09-07 00:00:00',
                'trainer' => 'Elvin Y. Baguio',
                'nttc' => 'NTTC No. 191907461200291',
                'expiration_date_of_nttc' => '13/06/2024',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0013',
                'name_of_institution' => 'Provincial Training Center - Dumaguete',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Jesila A. Ocariza - Center Administrator',
                'address' => 'Barangay Candau-ay, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.32125056,
                'longitude_point' => 123.2596064,
                'tel_no' => '(035) 422-9481',
                'e_mail_address' => 'ptc.dumaguete@tesda.gov.ph',
                'type_of_institution' => 'Public',
                'classification_of_institution' => 'TTI',
                'status' => 'WTR-MTP',
                'sector' => 'Construction',
                'course_registered_program' => 'Tile Setting NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '117 Hours',
                'program_reg_no' => 'WTR No. MTP-202307CONTIL218-129',
                'date_issued' => '2023-08-25 00:00:00',
                'expiration_date' => '2027-09-07 00:00:00',
                'trainer' => 'Elvin Y. Baguio',
                'nttc' => 'NTTC No. 191907461200293',
                'expiration_date_of_nttc' => '06/13/2024',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0013',
                'name_of_institution' => 'Provincial Training Center - Dumaguete',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Jesila A. Ocariza - Center Administrator',
                'address' => 'Barangay Candau-ay, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.32125056,
                'longitude_point' => 123.2596064,
                'tel_no' => '(035) 422-9481',
                'e_mail_address' => 'ptc.dumaguete@tesda.gov.ph',
                'type_of_institution' => 'Public',
                'classification_of_institution' => 'TTI',
                'status' => 'WTR-MTP',
                'sector' => 'Agriculture, Forestry and Fishery',
                'course_registered_program' => 'Agroentrepreneurship NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '239 Hours',
                'program_reg_no' => 'WTR No. MTP-202307AFFAGE217-148',
                'date_issued' => '2024-04-03 00:00:00',
                'expiration_date' => '2029-04-04 00:00:00',
                'trainer' => 'Beth Aimee D. Tubog
Emmalyn B. Carreon
Ma. Evelyn A. Tuisa
Gladys T. Deleña
Roberto P. Silva',
                'nttc' => 'NTTC No. 191807461200412
NTTC No. 221707461200239
PTTC No. 2207460200005
PTTC No. 2207460200006
PTTC No. 2207460200011',
                'expiration_date_of_nttc' => '9/12/2024
10/15/2026
6/23/2024
6/23/2024
9/26/2024',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0011',
                'name_of_institution' => 'Sto. Niño Skills Training & Assessment Center Incorporated',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Joel S. Vidal / President',
                'address' => '206 West Rovira Road Pulantubig Dumaguete City Negros Oriental 6200',
                'latitude_point' => 9.326378153,
                'longitude_point' => 123.2970677,
                'tel_no' => '(035) 422-8378 / 09063135543',
                'e_mail_address' => 'stoninotrainingandassessment@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Social, Community Development and Other Services',
                'course_registered_program' => 'Bookkeeping NC III - Mobile Training Program',
                'pgf_level' => 'NC III',
                'duration' => '292 Hours',
                'program_reg_no' => 'WTR No. MTP-202307SOCBKP307-162',
                'date_issued' => '2023-12-27 00:00:00',
                'expiration_date' => '2028-08-10 00:00:00',
                'trainer' => 'Richie B. Bungart',
                'nttc' => 'NTTC No. 232307461300112',
                'expiration_date_of_nttc' => '25/01/2025',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0011',
                'name_of_institution' => 'Sto. Niño Skills Training & Assessment Center Incorporated',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Joel S. Vidal II / President',
                'address' => '206 West Rovira Road Pulantubig Dumaguete City Negros Oriental 6200',
                'latitude_point' => 9.326378153,
                'longitude_point' => 123.2970677,
                'tel_no' => '(035) 422-8378 / 09063135543',
                'e_mail_address' => null,
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Automotive and Land Transportation',
                'course_registered_program' => 'Driving NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '118 Hours',
                'program_reg_no' => 'WTR No. MTP-202407ALTDRV204-010',
                'date_issued' => '2024-01-26 00:00:00',
                'expiration_date' => '2028-08-10 00:00:00',
                'trainer' => 'Jerome A. Zamora',
                'nttc' => 'NTTC No. 212007461200057',
                'expiration_date_of_nttc' => '17/12/2025',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0009',
                'name_of_institution' => 'Silliman University',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Betty Cernol-McCann, Ph.D., Rpsy, CSSP / President',
                'address' => 'Dumaguete City, Negros Oriental',
                'latitude_point' => 9.311966863,
                'longitude_point' => 123.3073819,
                'tel_no' => '(035) 422-6002',
                'e_mail_address' => null,
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'HEI',
                'status' => 'WTR-MTP',
                'sector' => 'Agriculture, Forestry and Fishery',
                'course_registered_program' => 'Animal Production (Poultry-Chicken) NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '226 Hours',
                'program_reg_no' => 'WTR No. MTP-202407AFFAPP213-020',
                'date_issued' => '2024-03-22 00:00:00',
                'expiration_date' => '2029-01-19 00:00:00',
                'trainer' => 'John  Albert Branzuela Ungson',
                'nttc' => 'NTTC No. 241907461200079',
                'expiration_date_of_nttc' => '17/12/2028',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0009',
                'name_of_institution' => 'Silliman University',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Betty Cernol-McCann, Ph.D., Rpsy, CSSP / President',
                'address' => 'Dumaguete City, Negros Oriental',
                'latitude_point' => 9.311966863,
                'longitude_point' => 123.3073819,
                'tel_no' => '(035) 422-6002',
                'e_mail_address' => null,
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'HEI',
                'status' => 'WTR-MTP',
                'sector' => 'Agriculture, Forestry and Fishery',
                'course_registered_program' => 'Animal Production (Swine) NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '306 Hours',
                'program_reg_no' => 'WTR No. MTP-202407AFFAPS213-021',
                'date_issued' => '2024-03-22 00:00:00',
                'expiration_date' => '2029-01-19 00:00:00',
                'trainer' => 'Justin Philip Ginggoyon Valencia',
                'nttc' => 'NTTC No. 231907461200508',
                'expiration_date_of_nttc' => '31/08/2028',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0009',
                'name_of_institution' => 'Silliman University',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Betty Cernol-McCann, Ph.D., Rpsy, CSSP / President',
                'address' => 'Dumaguete City, Negros Oriental',
                'latitude_point' => 9.311966863,
                'longitude_point' => 123.3073819,
                'tel_no' => '(035) 422-6002',
                'e_mail_address' => 'tevec@su.edu.ph and blanchiemutzurrum@su.edu.ph',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'HEI',
                'status' => 'WTR-MTP',
                'sector' => 'Agriculture, Forestry and Fishery',
                'course_registered_program' => 'Organic Agriculture Production NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '232 Hours',
                'program_reg_no' => 'WTR No. MTP-202407AFFOAP212-023',
                'date_issued' => '2024-04-11 00:00:00',
                'expiration_date' => '2028-08-03 00:00:00',
                'trainer' => 'Dorcas S. Panangganan',
                'nttc' => 'NTTC No. 211707461200460',
                'expiration_date_of_nttc' => '08/11/2026',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '1st',
                'municipality' => 'Guihulngan City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0016',
                'name_of_institution' => 'ZN Global Knowledge and Skills, Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Jesamyl D. Velasco - President',
                'address' => 'S. Villegas St., Poblacion, Guihulngan City, Negros Oriental',
                'latitude_point' => 10.11793882,
                'longitude_point' => 123.2696412,
                'tel_no' => '09971879449 / 
 09198985063',
                'e_mail_address' => 'znglobal.guihulngan@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Human Health/ Health Care',
                'course_registered_program' => 'Hilot (Wellness Massage) NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '120 Hours',
                'program_reg_no' => 'WTR No. MTP-202407HHCHIL208-024',
                'date_issued' => '2024-04-23 00:00:00',
                'expiration_date' => '2029-02-16 00:00:00',
                'trainer' => 'Rodelo T. Cabilin',
                'nttc' => 'NTTC No. 201909721200116',
                'expiration_date_of_nttc' => '02/03/2025',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0021',
                'name_of_institution' => 'Teamskills Technological Institute, Inc.',
                'formerly_name_of_tvi' => '(Formerly: Teamskills School for Culinary Arts and Hospitality Management, Inc.)',
                'name_of_institution_s_head' => 'Ariel D. Ronato, D.B.A. - President/CEO',
                'address' => '3rd Floor, Cecilia Building, Capitol Area, North Road, Daro, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.314098122,
                'longitude_point' => 123.3034628,
                'tel_no' => '(035) 4226159 /
 09175535507 / 09989788731',
                'e_mail_address' => 'info@team-skills.com     
teamskills.acenter@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Tourism',
                'course_registered_program' => 'Barista NC II - Mobile Training Program',
                'pgf_level' => null,
                'duration' => '178 Hours',
                'program_reg_no' => 'WTR No. MTP-202407TRSBRT213-029',
                'date_issued' => '2024-06-06 00:00:00',
                'expiration_date' => '2029-01-19 00:00:00',
                'trainer' => 'Ariel C. Ronato
Tina M. Ronato
Elrey Elmoore C. Abella
Angelo S. Salvoro',
                'nttc' => 'NTTC No. 221907461200032
NTTC No. 222207461200165
NTTC No. 232107461200262
NTTC No. 232307461200554',
                'expiration_date_of_nttc' => '1/9/2027
2/2/2027
9/25/2027
6/4/2028',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '1st',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0030',
                'name_of_institution' => 'Philippine Call Center Institute Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Kristelle Lynne P. Ong, Center Manager',
                'address' => '2/F, Doña Milagros Bldg., Sta. Rosa St., Dumaguete City, Negros Oriental',
                'latitude_point' => 9.30403785,
                'longitude_point' => 123.3078172,
                'tel_no' => '035-4210834, 09362125218, \'09088123684',
                'e_mail_address' => 'kristelleong@yahoo.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Information and Communication Technology',
                'course_registered_program' => 'Contact Center Services NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '144 Hours',
                'program_reg_no' => 'WTR No. MTP-202407ICTCCS214-045',
                'date_issued' => '2024-10-24 00:00:00',
                'expiration_date' => '2029-03-18 00:00:00',
                'trainer' => 'Jelo R. Silvano
Ludy Mae G. Bulahan
Luchie B. Stemper, 
Buena Asuncion D. San Marte, 
Doinita C. Bensing,
Adell T. Pacudan',
                'nttc' => 'Not indicated',
                'expiration_date_of_nttc' => 'Not indicated',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0022',
                'name_of_institution' => 'Metro Dumaguete College Inc.',
                'formerly_name_of_tvi' => '(Formerly: FOUR WD COMPUTER TRAINING CENTER, INC.)',
                'name_of_institution_s_head' => 'Dr. Delma P. Manila, DPA, CESO V / President',
                'address' => 'E.J. Blanco Drive Extension, Brgy. Daro, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.31933516,
                'longitude_point' => 123.2912191,
                'tel_no' => '(035) 4229728 / 2259170 / 4226341 / 4224605 / 09177008455',
                'e_mail_address' => 'mdctechvoc@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'TVET',
                'course_registered_program' => 'Trainers Methodology Level I (Trainer/Assessor) - Mobile Training Program',
                'pgf_level' => 'Level I',
                'duration' => '264 Hours',
                'program_reg_no' => 'WTR No. MTP-202407TVETRM111-049',
                'date_issued' => '2024-11-19 00:00:00',
                'expiration_date' => '2028-08-02 00:00:00',
                'trainer' => 'Margielen P. Alcoreza
Emmalyn B. Carreon
Edlyn P. Casal',
                'nttc' => 'TMC No. 20074601000019
TMC No. 23074601000012
TMC No. 23074601012100',
                'expiration_date_of_nttc' => '7/1/2025
2/19/2028
6/1/2028',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0022',
                'name_of_institution' => 'Metro Dumaguete College Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Dr. Delma P. Manila, DPA, CESO V / President',
                'address' => 'E.J. Blanco Drive Extension, Brgy. Daro, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.31933516,
                'longitude_point' => 123.2912191,
                'tel_no' => '(035) 4229728 / 2259170 / 4226341 / 4224605 / 09177008455',
                'e_mail_address' => 'mdctechvoc@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Tourism',
                'course_registered_program' => 'Bread and Pastry Production NC II - Mobile Training Program',
                'pgf_level' => 'NC I',
                'duration' => '141 Hours',
                'program_reg_no' => 'WTR No. MTP-202407TRSBPP209-050',
                'date_issued' => '2024-11-27 00:00:00',
                'expiration_date' => '2029-01-19 00:00:00',
                'trainer' => 'Margielen P. Alcoreza 
Baby Jean S. Baligasa 
Gina A. Ronidna',
                'nttc' => 'NTTC No. 202007461200343
NTTC No. 221807461200501
NTTC No. 221707461200014',
                'expiration_date_of_nttc' => '6/24/2025
10/6/2027
5/30/2026',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0022',
                'name_of_institution' => 'Metro Dumaguete College Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Dr. Delma P. Manila, DPA, CESO V / President',
                'address' => 'E.J. Blanco Drive Extension, Brgy. Daro, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.31933516,
                'longitude_point' => 123.2912191,
                'tel_no' => '(035) 4229728 / 2259170 / 4226341 / 4224605 / 09177008455',
                'e_mail_address' => 'mdctechvoc@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Social, Community Development and Other Services',
                'course_registered_program' => 'Bookkeeping NC III - Mobile Training Program',
                'pgf_level' => 'NC III',
                'duration' => '438 Hours',
                'program_reg_no' => 'WTR No. MTP-202407SOCBKP307-051',
                'date_issued' => '2024-11-27 00:00:00',
                'expiration_date' => '2029-05-27 00:00:00',
                'trainer' => 'Delma P. Manila',
                'nttc' => 'NTTC No. 242207461300083',
                'expiration_date_of_nttc' => '06/06/2028',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0013',
                'name_of_institution' => 'Provincial Training Center - Dumaguete',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Jesila A. Ocariza - Center Administrator',
                'address' => 'Barangay Candau-ay, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.32125056,
                'longitude_point' => 123.2596064,
                'tel_no' => '(035) 422-9481',
                'e_mail_address' => 'ptc.dumaguete@tesda.gov.ph',
                'type_of_institution' => 'Public',
                'classification_of_institution' => 'TTI',
                'status' => 'WTR-MTP',
                'sector' => 'TVET',
                'course_registered_program' => 'Trainers Methodology Level I (Trainer/Assessor) - Mobile Training Program',
                'pgf_level' => 'Level I',
                'duration' => '364 Hours',
                'program_reg_no' => 'WTR No. MTP-202407TVETRM111-052',
                'date_issued' => '2024-12-02 00:00:00',
                'expiration_date' => '2027-09-07 00:00:00',
                'trainer' => 'Margielen P. Alcoreza
Emmalyn B. Carreon
Edlyn P. Casal',
                'nttc' => 'TMC No. 20074601000019
TMC No. 23074601000012
TMC No. 23074601012100',
                'expiration_date_of_nttc' => '6/24/2025
2/19/2028
6/1/2028',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0011',
                'name_of_institution' => 'Sto. Niño Skills Training & Assessment Center Incorporated',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Annabelle C. Vidal, School Administrator',
                'address' => '206 West Rovira Road Pulantubig Dumaguete City Negros Oriental 6200',
                'latitude_point' => 9.326378153,
                'longitude_point' => 123.2970677,
                'tel_no' => '(035) 422-8378 / 09063135543',
                'e_mail_address' => 'stoninotrainingandassessment@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Human Health/ Health Care',
                'course_registered_program' => 'Caregiving NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '786 Hours',
                'program_reg_no' => 'WTR No. MTP-202507HHCCGV207-003',
                'date_issued' => '2025-01-17 00:00:00',
                'expiration_date' => '2028-08-10 00:00:00',
                'trainer' => 'Jurez Lilybeth Z. Fernandez',
                'nttc' => 'NTTC No. 242207461200717',
                'expiration_date_of_nttc' => '28/02/2029',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '1st',
                'municipality' => 'Guihulngan City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0004',
                'name_of_institution' => 'Guihulngan Satellite Skills Development Center',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Roberto T. Bustamante, Executive Director',
                'address' => 'Public Market, Guihulngan City, Negros Oriental',
                'latitude_point' => 10.13170829,
                'longitude_point' => 123.2733288,
                'tel_no' => '(035) 3361440/ 410-3098',
                'e_mail_address' => 'gssdc.guihulngan@yahoo.com',
                'type_of_institution' => 'Public',
                'classification_of_institution' => 'LGU',
                'status' => 'WTR-MTP',
                'sector' => 'Garments',
                'course_registered_program' => 'Dressmaking NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '275 Hours',
                'program_reg_no' => 'WTR No. MTP-202507GRMDRM205-016',
                'date_issued' => '2025-05-26 00:00:00',
                'expiration_date' => '2029-02-28 00:00:00',
                'trainer' => 'Michelle S. Montemayor',
                'nttc' => 'NTTC No. 221807461200480',
                'expiration_date_of_nttc' => '02/09/2027',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Bais City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0035',
                'name_of_institution' => 'Rams Art Training and Assessment Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Ramon E. Calumpang',
                'address' => 'Km 50, National Highway (Near DPWH Weighbridge) Brgy. Tamisu, Bais City, Negros Oriental',
                'latitude_point' => 9.629917044,
                'longitude_point' => 123.097848,
                'tel_no' => '(035) 4029837',
                'e_mail_address' => 'ramsartbais@gamil.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Tourism',
                'course_registered_program' => 'Bread and Pastry Production NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '141 Hours',
                'program_reg_no' => 'WTR No. MTP-2025-07-46-TRSBPP209-027',
                'date_issued' => '2025-09-29 00:00:00',
                'expiration_date' => '2029-03-18 00:00:00',
                'trainer' => 'Agnes M. Niere
Judelyn P. Rebutazo',
                'nttc' => 'NTTC No. 232307461200334
NTTC No. 252407461200078',
                'expiration_date_of_nttc' => 'May 25, 2028
March 12, 2029',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Bais City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0035',
                'name_of_institution' => 'Rams Art Training and Assessment Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Ramon E. Calumpang',
                'address' => 'Km 50, National Highway (Near DPWH Weighbridge) Brgy. Tamisu, Bais City, Negros Oriental',
                'latitude_point' => 9.629917044,
                'longitude_point' => 123.097848,
                'tel_no' => '(035) 4029837',
                'e_mail_address' => 'ramsartbais@gamil.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Social, Community Development and Other Services',
                'course_registered_program' => 'Bookkeeping NC III - Mobile Training Program',
                'pgf_level' => 'NC III',
                'duration' => '438 Hours',
                'program_reg_no' => 'WTR No. MTP-2025-07-46-SOCBKP307-028',
                'date_issued' => '2025-09-29 00:00:00',
                'expiration_date' => '2029-11-16 00:00:00',
                'trainer' => 'Joan A. Amposta',
                'nttc' => 'NTTC No. 242407461300637',
                'expiration_date_of_nttc' => 'July 27, 2029',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Bais City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0035',
                'name_of_institution' => 'Rams Art Training and Assessment Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Ramon E. Calumpang',
                'address' => 'Km 50, National Highway (Near DPWH Weighbridge) Brgy. Tamisu, Bais City, Negros Oriental',
                'latitude_point' => 9.629917044,
                'longitude_point' => 123.097848,
                'tel_no' => '(035) 4029837',
                'e_mail_address' => 'ramsartbais@gamil.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Electrical and Electronics',
                'course_registered_program' => 'Electrical Installation and Maintenance NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '196 Hours',
                'program_reg_no' => 'WTR No. MTP-2025-07-46-ELCEIM215-029',
                'date_issued' => '2025-09-29 00:00:00',
                'expiration_date' => '2029-09-26 00:00:00',
                'trainer' => 'Francis E. Cadallo
Ramon E. Calumpang',
                'nttc' => 'NTTC No. 242107461200311
NTTC No. 232307461200265',
                'expiration_date_of_nttc' => 'March 19, 2029
December 2, 2027',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Bayawan City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => 'Not Found',
                'name_of_institution' => 'Integrated Development Training and Assessment Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Elma C. Tanasan, President',
                'address' => 'Sitio Buli Buli Banga, City of Bayawan (Tulong), Negros Oriental, Region VII (Central Visayas), 6221',
                'latitude_point' => 9.388800738,
                'longitude_point' => 122.7956269,
                'tel_no' => '0916-763-2822',
                'e_mail_address' => 'atstaci2023@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Agriculture, Forestry and Fishery',
                'course_registered_program' => 'Agroentrepreneurship NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '239 Hours',
                'program_reg_no' => 'WTR No. MTP 2025-07-46-AFFAGE217-032',
                'date_issued' => '2025-11-07 00:00:00',
                'expiration_date' => '2029-12-14 00:00:00',
                'trainer' => 'Kenneth John Baliquig',
                'nttc' => 'NTTC No. 242407461200405',
                'expiration_date_of_nttc' => '30-May-29',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Bayawan City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => 'Not Found',
                'name_of_institution' => 'Integrated Development Training and Assessment Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Elma C. Tanasan, President',
                'address' => 'Sitio Buli Buli Banga, City of Bayawan (Tulong), Negros Oriental, Region VII (Central Visayas), 6221',
                'latitude_point' => 9.388800738,
                'longitude_point' => 122.7956269,
                'tel_no' => '0916-763-2822',
                'e_mail_address' => 'atstaci2023@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Social, Community Development and Other Services',
                'course_registered_program' => 'Bookkeeping NC III - Mobile Training Program',
                'pgf_level' => 'NC III',
                'duration' => '292 Hours',
                'program_reg_no' => 'WTR No. MTP 2025-07-46-SOCBKP307-033',
                'date_issued' => '2025-11-07 00:00:00',
                'expiration_date' => '2029-12-14 00:00:00',
                'trainer' => 'Kenneth John Baliquig',
                'nttc' => 'NTTC No. 242407461300402',
                'expiration_date_of_nttc' => '11-Mar-27',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Bayawan City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => 'Not Found',
                'name_of_institution' => 'Integrated Development Training and Assessment Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Elma C. Tanasan, President',
                'address' => 'Sitio Buli Buli Banga, City of Bayawan (Tulong), Negros Oriental, Region VII (Central Visayas), 6221',
                'latitude_point' => 9.388800738,
                'longitude_point' => 122.7956269,
                'tel_no' => '0916-763-2822',
                'e_mail_address' => 'atstaci2023@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Automotive and Land Transportation',
                'course_registered_program' => 'Driving NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '118 Hours',
                'program_reg_no' => 'WTR No. MTP 2025-07-46-ALTDRV204-034',
                'date_issued' => '2025-11-07 00:00:00',
                'expiration_date' => '2029-12-14 00:00:00',
                'trainer' => 'Kenneth John Baliquig',
                'nttc' => 'NTTC No. 242407461200403',
                'expiration_date_of_nttc' => '02-Sep-27',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '3rd',
                'municipality' => 'Bayawan City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0002',
                'name_of_institution' => 'Southern Tech College Foundation Incorporated',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Ion Joseph T. Bollos, MSEM - President',
                'address' => 'National Highway, Villareal, Bayawan City, Negros Oriental',
                'latitude_point' => 9.359063707,
                'longitude_point' => 122.8214852,
                'tel_no' => '(035) 531-0879',
                'e_mail_address' => 'southerntechcollegebayawan@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Social, Community Development and Other Services',
                'course_registered_program' => 'Bookkeeping NC III - Mobile Training Program',
                'pgf_level' => 'NC III',
                'duration' => '292 Hours',
                'program_reg_no' => 'WTR No. MTP 2025-07-46-SOCBKP307-039',
                'date_issued' => '2025-12-10 00:00:00',
                'expiration_date' => '2028-12-12 00:00:00',
                'trainer' => 'Rosemarie O. Guardiano',
                'nttc' => 'NTTC No. 231907461300246',
                'expiration_date_of_nttc' => '12/04/2028',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '3rd',
                'municipality' => 'Bayawan City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0002',
                'name_of_institution' => 'Southern Tech College Foundation Incorporated',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Ion Joseph T. Bollos, MSEM - President',
                'address' => 'National Highway, Villareal, Bayawan City, Negros Oriental',
                'latitude_point' => 9.359063707,
                'longitude_point' => 122.8214852,
                'tel_no' => '(035) 531-0879',
                'e_mail_address' => 'southerntechcollegebayawan@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Electrical and Electronics',
                'course_registered_program' => 'Computer Systems Servicing NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '280 Hours',
                'program_reg_no' => 'WTR No. MTP 2025-07-46-ELCCSS213-040',
                'date_issued' => '2025-12-10 00:00:00',
                'expiration_date' => '2028-12-12 00:00:00',
                'trainer' => 'Julie Mae J. Librado',
                'nttc' => 'NTTC No. 242207461200690',
                'expiration_date_of_nttc' => '29/08/2029',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0011',
                'name_of_institution' => 'Sto. Niño Skills Training & Assessment Center Incorporated',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Annabelle C. Vidal, Administrator',
                'address' => '206 West Rovira Road Pulantubig Dumaguete City Negros Oriental 6200',
                'latitude_point' => 9.326396272,
                'longitude_point' => 123.2970941,
                'tel_no' => '(035) 422-8378 / 09063135543',
                'e_mail_address' => 'stoninotrainingandassessment@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Agriculture, Forestry and Fishery',
                'course_registered_program' => 'Agroentrepreneurship NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '239 Hours',
                'program_reg_no' => 'WTR No. MTP 2025-07-46-AFFAGE217-041',
                'date_issued' => '2025-12-10 00:00:00',
                'expiration_date' => '2025-12-17 00:00:00',
                'trainer' => 'Richie B. Bungart
Judith D. Baguio
Rogir B. Agir',
                'nttc' => 'NTTC No. 221707461200186
NTTC No. 242307461200489
NTTC No. 242007461200627',
                'expiration_date_of_nttc' => '10/16/2026
12/22/2028
8/30/2029',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0021',
                'name_of_institution' => 'Teamskills Technological Institute, Inc.',
                'formerly_name_of_tvi' => '"(Formerly:
Teamskills School for Culinary Arts and Hopitality Management, Inc."',
                'name_of_institution_s_head' => 'Ariel D. Ronato, D.B.A. - President/CEO',
                'address' => '3rd Floor, Cecilia Building, Capitol Area, North Road, Daro, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.30910084,
                'longitude_point' => 123.2911675,
                'tel_no' => '(035) 4226159 /
 09175535507 / 09989788731',
                'e_mail_address' => 'info@team-skills.com     
teamskills.acenter@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'TVET',
                'course_registered_program' => 'Trainers Methodology Level I (Trainer/Assessor) - Mobile Training Program',
                'pgf_level' => 'Level I',
                'duration' => '264 Hours',
                'program_reg_no' => 'WTR No. MTP 2025-07-46-TVETRM111-042',
                'date_issued' => '2025-12-10 00:00:00',
                'expiration_date' => '2027-10-16 00:00:00',
                'trainer' => 'Ariel D. Ronato
Floridel C. Pelin
Luz L. Borromeo
Rowell L. Panuncial
Mark Alexander A. Reposo
Elrey Elmoore C. Abella',
                'nttc' => 'TMC25074601000058
TMC-23071201010768
TMC-23072201000616
TMC23072201001009
TMC-21074601000019
TMC-21074601000007',
                'expiration_date_of_nttc' => 'January 8, 2030
November 20, 2028
February 21, 2028
April 11, 2028
September 20, 2026
February 10, 2026',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Bayawan City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => 'Not Found',
                'name_of_institution' => 'Armstrong Career and Technical Education Institute Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Larry Neil C. Abalajon, President',
                'address' => 'Brgy. Kalumboyan, Bayawan City, Negros Oriental, 6221',
                'latitude_point' => 9.51076,
                'longitude_point' => 122.80732,
                'tel_no' => '0997-067-5423 / 0922-770-6451',
                'e_mail_address' => 'actei.edu1118@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Agriculture, Forestry and Fishery',
                'course_registered_program' => 'Organic Agriculture Production NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '232 Hours',
                'program_reg_no' => 'WTR No. MTP 202507AFFOAP212-052',
                'date_issued' => '2025-12-26 00:00:00',
                'expiration_date' => '2029-02-23 00:00:00',
                'trainer' => 'Greg A. Cadapan
Allan Eugine Q. Lagradilla
Michel Padpad
Francis B. Betchido
Dereck James M. Requina',
                'nttc' => 'NTTC No. 231907461200333
NTTC No. 222007611200151
NTTC No. 232207461200392
NTTC No. 221907461200228
NTTC No. 221807461200551',
                'expiration_date_of_nttc' => 'June 14, 2028
February 21, 2027
April 28, 2028
March 18, 2027
September 6, 2027',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Bais City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0012',
                'name_of_institution' => 'Abellana Technical and Vocational Center, Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Fe L. Abellana, President',
                'address' => 'Abellana\'s Building, Osmena Street , Brgy. 2 Bais City, Negros Oriental',
                'latitude_point' => 9.591613909,
                'longitude_point' => 123.1211719,
                'tel_no' => '(035) 5313732 / 4023717 / 09351633419',
                'e_mail_address' => 'abellanastechcenter@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Human Health/ Health Care',
                'course_registered_program' => 'Hilot (Wellness Massage) NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '120 Hours',
                'program_reg_no' => 'WTR No. MTP 202607HHCHIL208-007',
                'date_issued' => '2026-03-04 00:00:00',
                'expiration_date' => '2029-04-03 00:00:00',
                'trainer' => 'Monica R. Atay',
                'nttc' => 'NTTC No. 252209721200298',
                'expiration_date_of_nttc' => '22/06/2030',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Bais City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0012',
                'name_of_institution' => 'Abellana Technical and Vocational Center, Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Fe L. Abellana, President',
                'address' => 'Abellana\'s Building, Osmena Street , Brgy. 2 Bais City, Negros Oriental',
                'latitude_point' => 9.591613909,
                'longitude_point' => 123.1211719,
                'tel_no' => '(035) 5313732 / 4023717 / 09351633419',
                'e_mail_address' => 'abellanastechcenter@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Social, Community Development and Other Services',
                'course_registered_program' => 'Bookkeeping NC III - Mobile Training Program',
                'pgf_level' => 'NC III',
                'duration' => '292 Hours',
                'program_reg_no' => 'WTR No. MTP 202607SOCBKP307-008',
                'date_issued' => '2026-03-04 00:00:00',
                'expiration_date' => '2029-04-03 00:00:00',
                'trainer' => 'Ryan Cris M. Alabo',
                'nttc' => 'NTTC No. 242407461300485',
                'expiration_date_of_nttc' => '22/12/2028',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '1st',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0019',
                'name_of_institution' => 'Negor Professional Skills Institute and Assessment Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'HENRIETTA N. ZERNA - President',
                'address' => '2nd Floor D&J Building Dr. V. Locsin St. Poblacion No. 4 (Barangay 4) Dumaguete City (Capital), Negros Oriental, Region VII, Philippines, 6200',
                'latitude_point' => 9.306966843,
                'longitude_point' => 123.3049508,
                'tel_no' => '9176400235',
                'e_mail_address' => null,
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Human Health/ Health Care',
                'course_registered_program' => 'Hilot (Wellness Massage) NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '120 Hours',
                'program_reg_no' => 'WTR No. MTP 202607HHCHIL208-009',
                'date_issued' => '2026-03-04 00:00:00',
                'expiration_date' => '2029-05-23 00:00:00',
                'trainer' => 'Fred S. Jumawan
Cristopher P. Labial',
                'nttc' => 'NTTC No. 231807611200237
NTTC No. 231906191205093',
                'expiration_date_of_nttc' => 'April 16, 2028
July 13, 2028',
            ],
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_instittution_identification' => '0746-0009',
                'name_of_institution' => 'Silliman University',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Blanchie M. Utzurrum, MPA - Head SU TEVEC',
                'address' => 'Leopoldo T. Ruiz Administration Hall, Silliman University, Hibbard Avenue, Dumaguete City, Philippines',
                'latitude_point' => 9.31188509,
                'longitude_point' => 123.3072783,
                'tel_no' => '0905-2311-150 / 0917-880-1901',
                'e_mail_address' => 'administration@su.edu.ph',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'HEI',
                'status' => 'WTR-MTP',
                'sector' => 'Social, Community Development and Other Services',
                'course_registered_program' => 'Early Childhood Care and Development Services NC III - Mobile Training Program',
                'pgf_level' => 'NC III',
                'duration' => '298 Hours',
                'program_reg_no' => 'WTR No. MTP 202607SOCECD325-012',
                'date_issued' => '2026-04-22 00:00:00',
                'expiration_date' => '2030-12-27 00:00:00',
                'trainer' => 'Blanchie M. Utzurrum',
                'nttc' => 'NTTC No. 252407461300555',
                'expiration_date_of_nttc' => '07/10/2030',
            ],
        ];

        foreach (array_chunk($rows, 50) as $chunk) {
            DB::table('t_2026_negros_oriental')->insert($chunk);
        }
    }
}