<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class T2026SiquijorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rows = [
            [
                'region' => 'VII',
                'province' => 'Siquijor',
                'congressional_district' => 'Lone',
                'municipality' => 'Siquijor',
                'municipality_class' => '4th',
                'unique_instittution_identification' => 'Not Found',
                'name_of_institution' => 'Carmelite College of Siquijor, Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Sr. Mila Margaret V. Motegrejo',
                'address' => 'Balasbalas, Cang-Alwang, Tinago, Siquijor, Siquijor',
                'latitude_point' => 9.213684924,
                'longitude_point' => 123.4803531,
                'tel_no' => '035-344-2098 / (035) 542-6276',
                'e_mail_address' => 'ccsi.official@carmelitecollegesiquijor.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR',
                'sector' => 'Electrical and Electronics',
                'course_registered_program' => 'Computer Systems Servicing NC II',
                'pgf_level' => 'NC II',
                'duration' => '360 hours',
                'program_reg_no' => '20220761ELCCSS213092',
                'date_issued' => '2024-04-19 00:00:00',
                'expiration_date' => '2029-04-22 00:00:00',
                'trainer' => 'Kenneth P. Llorente',
                'nttc' => '161408000000000',
                'expiration_date_of_nttc' => 'Not indicated',
            ],
            [
                'region' => 'VII',
                'province' => 'Siquijor',
                'congressional_district' => 'Lone',
                'municipality' => 'Lazi',
                'municipality_class' => '4th',
                'unique_instittution_identification' => 'Not Found',
                'name_of_institution' => 'PSP Technological Institute Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Pierre S. Pakilit',
                'address' => 'Pakilit Residence Alvarico Tigbawan (Pob.) Lazi, Siquijor, Region VII, Philippines 6228',
                'latitude_point' => 9.218691948,
                'longitude_point' => 123.5189104,
                'tel_no' => '0965-774-2490',
                'e_mail_address' => 'psptechnology2019@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR',
                'sector' => 'Automotive and Land Transportation',
                'course_registered_program' => 'Driving NC II',
                'pgf_level' => 'NC II',
                'duration' => '118 hours',
                'program_reg_no' => '20190761ALTDRV204103',
                'date_issued' => '2023-12-28 00:00:00',
                'expiration_date' => '2028-12-29 00:00:00',
                'trainer' => 'Arnold M. Magtahas, Orlando J. Gio, Excel C. Cabanag',
                'nttc' => 'NTTC No. 191907611200444 No.181807461200398, No. 191507461200037',
                'expiration_date_of_nttc' => '08-Oct-23, Aug. 28, 2023, Oct. 16, 2023',
            ],
            [
                'region' => 'VII',
                'province' => 'Siquijor',
                'congressional_district' => 'Lone',
                'municipality' => 'Lazi',
                'municipality_class' => '4th',
                'unique_instittution_identification' => 'Not Found',
                'name_of_institution' => 'PSP Technological Institute Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Pierre S. Pakilit',
                'address' => 'Pakilit Residence Alvarico Tigbawan (Pob.) Lazi, Siquijor, Region VII, Philippines 6228',
                'latitude_point' => 9.218691948,
                'longitude_point' => 123.5189104,
                'tel_no' => '0965-774-2490',
                'e_mail_address' => 'psptechnology2019@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR',
                'sector' => 'Electrical and Electronics',
                'course_registered_program' => 'Electrical Installation and Maintenance NC II',
                'pgf_level' => 'NC II',
                'duration' => '244 Hours',
                'program_reg_no' => '20220761ELCEIM215069',
                'date_issued' => '2023-12-28 00:00:00',
                'expiration_date' => '2028-12-29 00:00:00',
                'trainer' => 'Huberto V. Duran',
                'nttc' => 'NTTC No. 221807611200091',
                'expiration_date_of_nttc' => 'February 15, 2027',
            ],
            [
                'region' => 'VII',
                'province' => 'Siquijor',
                'congressional_district' => 'Lone',
                'municipality' => 'San Juan',
                'municipality_class' => '5th',
                'unique_instittution_identification' => 'Not Found',
                'name_of_institution' => 'Siquijor Language Academy Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Frelyn L. Pagente, CEO',
                'address' => 'Maite, San Juan, Siquijor, Region VII (Central Visayas), 6227',
                'latitude_point' => 9.151831975,
                'longitude_point' => 123.5013812,
                'tel_no' => '9279707007',
                'e_mail_address' => 'frelynpagente@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'RTP',
                'sector' => 'Others (Languages)',
                'course_registered_program' => 'ESL Beginner Course',
                'pgf_level' => 'N/A',
                'duration' => '120 Hours',
                'program_reg_no' => 'NTR No. 202207610024',
                'date_issued' => '2022-11-22 00:00:00',
                'expiration_date' => '2027-11-21 00:00:00',
                'trainer' => 'Jay Ann Amorsolo
Shiela Mae M. Caroro',
                'nttc' => 'TMC No. 22076101022381',
                'expiration_date_of_nttc' => 'Not indicated',
            ],
            [
                'region' => 'VII',
                'province' => 'Siquijor',
                'congressional_district' => 'Lone',
                'municipality' => 'Larena',
                'municipality_class' => '5th',
                'unique_instittution_identification' => 'Not Found',
                'name_of_institution' => 'CMC Institute of Business Management, Skills Training and Assessment Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Aida C. Madulara - President',
                'address' => 'North Poblacion, Larena, Siquijor',
                'latitude_point' => 9.278613093,
                'longitude_point' => 123.584607,
                'tel_no' => '9176710565',
                'e_mail_address' => 'madulara@yahoo.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR',
                'sector' => 'Tourism',
                'course_registered_program' => 'Events Management Services NC III',
                'pgf_level' => 'NC III',
                'duration' => '188 Hours',
                'program_reg_no' => 'WTR No. 20230761TRSEVM307006',
                'date_issued' => '2024-03-15 00:00:00',
                'expiration_date' => '2029-03-18 00:00:00',
                'trainer' => 'Ana Liza A. Baluran
Jovie D. Cabais',
                'nttc' => 'NTTC No. 211707121300387
NTTC No. 191907121300496',
                'expiration_date_of_nttc' => '19-Sep-26
5/24/2024',
            ],
            [
                'region' => 'VII',
                'province' => 'Siquijor',
                'congressional_district' => 'Lone',
                'municipality' => 'Larena',
                'municipality_class' => '5th',
                'unique_instittution_identification' => 'Not Found',
                'name_of_institution' => 'CMC Institute of Business Management, Skills Training and Assessment Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Aida C. Madulara - President',
                'address' => 'North Poblacion, Larena, Siquijor',
                'latitude_point' => 9.278613093,
                'longitude_point' => 123.584607,
                'tel_no' => '9176710565',
                'e_mail_address' => 'madulara@yahoo.com / cmcsiquijor.skillstraining@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR',
                'sector' => 'Tourism',
                'course_registered_program' => 'Food and Beverage Services NC II',
                'pgf_level' => 'NC II',
                'duration' => '436 Hours',
                'program_reg_no' => 'WTR No. 20230761TRSFBS213007',
                'date_issued' => '2024-03-15 00:00:00',
                'expiration_date' => '2029-03-18 00:00:00',
                'trainer' => 'Almarie M. Sumalpong',
                'nttc' => 'NTTC No. 211807611200303',
                'expiration_date_of_nttc' => '06/06/2026',
            ],
            [
                'region' => 'VII',
                'province' => 'Siquijor',
                'congressional_district' => 'Lone',
                'municipality' => 'Larena',
                'municipality_class' => '5th',
                'unique_instittution_identification' => 'Not Found',
                'name_of_institution' => 'CMC Institute of Business Management, Skills Training and Assessment Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Aida C. Madulara - President',
                'address' => 'North Poblacion, Larena, Siquijor',
                'latitude_point' => 9.278613093,
                'longitude_point' => 123.584607,
                'tel_no' => '9176710565',
                'e_mail_address' => 'madulara@yahoo.com / cmcsiquijor.skillstraining@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR',
                'sector' => 'Social, Community Development and Other Services',
                'course_registered_program' => 'Bookkeeping NC III',
                'pgf_level' => 'NC III',
                'duration' => '383 Hours',
                'program_reg_no' => '20230761SOCBKP307032',
                'date_issued' => '2023-04-13 00:00:00',
                'expiration_date' => '2028-04-12 00:00:00',
                'trainer' => 'Melissa C. Handumon
Jesie B. Dua',
                'nttc' => 'NTTC No. 221807121300196
NTTC No. 222207121300374',
                'expiration_date_of_nttc' => '4/6/2027
7/20/2027',
            ],
            [
                'region' => 'VII',
                'province' => 'Siquijor',
                'congressional_district' => 'Lone',
                'municipality' => 'Larena',
                'municipality_class' => '5th',
                'unique_instittution_identification' => 'Not Found',
                'name_of_institution' => 'CMC Institute of Business Management, Skills Training and Assessment Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Aida C. Madulara - President',
                'address' => 'North Poblacion, Larena, Siquijor',
                'latitude_point' => 9.278613093,
                'longitude_point' => 123.584607,
                'tel_no' => '9176710565',
                'e_mail_address' => 'madulara@yahoo.com / cmcsiquijor.skillstraining@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR',
                'sector' => 'Tourism',
                'course_registered_program' => 'Tourism Promotion Services NC II',
                'pgf_level' => 'NC II',
                'duration' => '76 Hours',
                'program_reg_no' => '20230761TRSTPS215059',
                'date_issued' => '2023-06-23 00:00:00',
                'expiration_date' => '2028-06-26 00:00:00',
                'trainer' => 'Gemma D. Adovo',
                'nttc' => 'NTTC No. 222207121200400',
                'expiration_date_of_nttc' => 'February 08, 2028',
            ],
            [
                'region' => 'VII',
                'province' => 'Siquijor',
                'congressional_district' => 'Lone',
                'municipality' => 'Larena',
                'municipality_class' => '5th',
                'unique_instittution_identification' => 'Not Found',
                'name_of_institution' => 'CMC Institute of Business Management, Skills Training and Assessment Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Aida C. Madulara - President',
                'address' => 'North Poblacion, Larena, Siquijor',
                'latitude_point' => 9.278613093,
                'longitude_point' => 123.584607,
                'tel_no' => '9176710565',
                'e_mail_address' => 'madulara@yahoo.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR',
                'sector' => 'Electrical and Electronics',
                'course_registered_program' => 'Computer Systems Servicing NC II',
                'pgf_level' => 'NC II',
                'duration' => '360 Hours',
                'program_reg_no' => 'WTR No. 20240761ELCCSS213045',
                'date_issued' => '2024-04-22 00:00:00',
                'expiration_date' => '2024-04-23 00:00:00',
                'trainer' => 'Rex V. Pinton',
                'nttc' => 'NTTC No. 222107611200202',
                'expiration_date_of_nttc' => '04/05/2027',
            ],
            [
                'region' => 'VII',
                'province' => 'Siquijor',
                'congressional_district' => 'Lone',
                'municipality' => 'Lazi',
                'municipality_class' => '4th',
                'unique_instittution_identification' => 'Not Found',
                'name_of_institution' => 'PSP Technological Institute Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Pierre S. Pakilit - President',
                'address' => 'Pakilit Residence Alvarico Tigbawan (Pob.) Lazi, Siquijor, Region VII, Philippines 6228',
                'latitude_point' => 9.135146101,
                'longitude_point' => 123.6337518,
                'tel_no' => '0965-774-2490',
                'e_mail_address' => 'psptechnology2019@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR',
                'sector' => 'Construction',
                'course_registered_program' => 'Carpentry NC II',
                'pgf_level' => 'NC II',
                'duration' => '301 Hours',
                'program_reg_no' => 'WTR No. 20240761CONCAR218058',
                'date_issued' => '2024-05-10 00:00:00',
                'expiration_date' => '2029-05-13 00:00:00',
                'trainer' => 'Edward P. Mariño',
                'nttc' => 'NTTC No. 232207461200054',
                'expiration_date_of_nttc' => '18/08/2027',
            ],
            [
                'region' => 'VII',
                'province' => 'Siquijor',
                'congressional_district' => 'Lone',
                'municipality' => 'Larena',
                'municipality_class' => '5th',
                'unique_instittution_identification' => 'Not Found',
                'name_of_institution' => 'SBR Technical Education Training Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Vic Ronald V. Patay, Branch Administrator',
                'address' => 'Basac, Larena, Siquijor',
                'latitude_point' => 9.219327971,
                'longitude_point' => 123.6155831,
                'tel_no' => '0965-145-2942',
                'e_mail_address' => 'sbr.siquijor24@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR',
                'sector' => 'Construction',
                'course_registered_program' => 'Heavy Equipment Operation (Hydraulic Excavator) NC II',
                'pgf_level' => 'NC II',
                'duration' => '221 hours',
                'program_reg_no' => 'WTR No. 20250761CONHEO219033',
                'date_issued' => '2025-03-19 00:00:00',
                'expiration_date' => '2030-03-20 00:00:00',
                'trainer' => 'Ronie N. Razona',
                'nttc' => 'NTTC No. 232007121200407',
                'expiration_date_of_nttc' => 'July 18, 2028',
            ],

            
        ];

        foreach (array_chunk($rows, 50) as $chunk) {
            DB::table('t_2026_negros_oriental')->insert($chunk);
        }
    }
}