<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class T2026NegrosOrientalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rows = [
            // Row 1
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0010',
                'name_of_institution' => 'Cuttin\' Loose Beauty Culture (CLBC) Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Maria Luz- Cole Havranek',
                'address' => 'Room 201 and 203, Bandera Bldg., Cervantes St., Brgy. Poblacion 8, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.301933736,
                'longitude_point' => 123.3040585,
                'tel_no' => '(035)4221944',
                'e_mail_address' => 'clbci.techvoc@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Human Health/ Health Care',
                'course_registered_program' => 'Hilot (Wellness Massage) NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '120 Hours',
                'program_reg_no' => 'WTR No. MTP-202307HHCHIL208-082',
                'date_issued' => '2023-12-11 00:00:00',
                'expiration_date' => '2028-12-12 00:00:00',
                'trainer' => "Myra A. Umbac\nTerence L. Havranek\nStanley Antonio D. Umbac",
                'nttc' => "TMC No. 20074601000013\nTMC No. 18074601000234\nTMC No. 19074601000117",
                'expiration_date_of_nttc' => "2025-05-03\n2023-10-19\n2024-06-07",
            ],
            // Row 2
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0007',
                'name_of_institution' => 'People Skills and Management Institute, Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Ariel D. Ronato - Chairman of the Board',
                'address' => '1F Bandera Bldg., 27 Cervantes St., Dumaguete City, Negros Oriental',
                'latitude_point' => 9.310555416,
                'longitude_point' => 123.3048972,
                'tel_no' => '(035) 420-9600',
                'e_mail_address' => null,
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Information and Communication Technology',
                'course_registered_program' => 'Contact Center Services NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '144 hours',
                'program_reg_no' => 'WTR No. MTP-202307ICTCCS214-088',
                'date_issued' => '2024-01-25 00:00:00',
                'expiration_date' => '2029-01-26 00:00:00',
                'trainer' => "Lovely Mae F. Glinogo\nLiezel Y. Macolbacol\nRolando D. Gadiane, Jr.",
                'nttc' => "TMC No. 22074601000082\nTMC No. 19074601000093\nTMC No. 20074601000023",
                'expiration_date_of_nttc' => "2027-06-12\n2024-03-28\n2025-09-01",
            ],
            // Row 3
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0008',
                'name_of_institution' => 'Foundation University Inc.',
                'formerly_name_of_tvi' => "(Vicente and Sofia Sinco Foundation, Inc.)\n(V.G. Sinco Educational Corporation)",
                'name_of_institution_s_head' => 'Vicente G. Sinco - President',
                'address' => 'Dr. Miciano Raod, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.306198793,
                'longitude_point' => 123.3014725,
                'tel_no' => '(035) 422-9167',
                'e_mail_address' => 'richie.bungart@foundationu.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'HEI',
                'status' => 'WTR-MTP',
                'sector' => 'Tourism',
                'course_registered_program' => 'Bread and Pastry Production NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '141 Hours',
                'program_reg_no' => 'WTR No. MTP-202307TRSBPP209-099',
                'date_issued' => '2024-01-26 00:00:00',
                'expiration_date' => '2029-01-29 00:00:00',
                'trainer' => "Antonio T. Bendal, Jr.\nJorie May J. Barraquias\nMeraflor T. Ventero",
                'nttc' => 'NTTC No. 211707221200170',
                'expiration_date_of_nttc' => '2026-10-03',
            ],
            // Row 4
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0008',
                'name_of_institution' => 'Foundation University Inc.',
                'formerly_name_of_tvi' => "(Vicente and Sofia Sinco Foundation, Inc.)\n(V.G. Sinco Educational Corporation)",
                'name_of_institution_s_head' => 'Vicente G. Sinco - President',
                'address' => 'Dr. Miciano Raod, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.306198793,
                'longitude_point' => 123.3014725,
                'tel_no' => '(035) 422-9167',
                'e_mail_address' => 'richie.bungart@foundationu.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'HEI',
                'status' => 'WTR-MTP',
                'sector' => 'Social, Community Development and Other Services',
                'course_registered_program' => 'Bookkeeping NC III - Mobile Training Program',
                'pgf_level' => 'NC III',
                'duration' => '292 Hours',
                'program_reg_no' => 'WTR No. MTP-202307SOCBKP307-100',
                'date_issued' => '2023-07-07 00:00:00',
                'expiration_date' => '2028-04-21 00:00:00',
                'trainer' => 'Richie B. Bungart',
                'nttc' => 'NTTC No. 232307461300112',
                'expiration_date_of_nttc' => '2028-01-25',
            ],
            // Row 5
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0008',
                'name_of_institution' => 'Foundation University Inc.',
                'formerly_name_of_tvi' => "(Vicente and Sofia Sinco Foundation, Inc.)\n(V.G. Sinco Educational Corporation)",
                'name_of_institution_s_head' => 'Vicente G. Sinco - President',
                'address' => 'Dr. Miciano Raod, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.306198793,
                'longitude_point' => 123.3014725,
                'tel_no' => '(035) 422-9167',
                'e_mail_address' => 'richie.bungart@foundationu.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'HEI',
                'status' => 'WTR-MTP',
                'sector' => 'Tourism',
                'course_registered_program' => 'Cookery NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '316 Hours',
                'program_reg_no' => 'WTR No. MTP-202307TRSCOK214-101',
                'date_issued' => '2024-01-26 00:00:00',
                'expiration_date' => '2029-01-29 00:00:00',
                'trainer' => "Antonio T. Bendal, Jr.\nJorie May J. Barraquias",
                'nttc' => 'NTTC No. 191907461200367',
                'expiration_date_of_nttc' => '2024-07-17',
            ],
            // Row 6
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0013',
                'name_of_institution' => 'Provincial Training Center - Dumaguete',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Jesila A. Ocariza - Center Administrator',
                'address' => 'Barangay Candau-ay, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.32125056,
                'longitude_point' => 123.2596064,
                'tel_no' => '(035) 422-9481',
                'e_mail_address' => 'ptc.dumaguete@tesda.gov.ph',
                'type_of_institution' => 'Public',
                'classification_of_institution' => 'TTI',
                'status' => 'WTR-MTP',
                'sector' => 'Construction',
                'course_registered_program' => 'Carpentry NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '301 Hours',
                'program_reg_no' => 'WTR No. MTP-202307CONCAR218-108',
                'date_issued' => '2023-07-21 00:00:00',
                'expiration_date' => '2027-09-07 00:00:00',
                'trainer' => 'Elvin Y. Baguio',
                'nttc' => 'NTTC No. 191907461200292',
                'expiration_date_of_nttc' => '2024-06-13',
            ],
            // Row 7
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0031',
                'name_of_institution' => 'Global Tech Manpower Institute Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Eduardo P. Mondarte - Administrator',
                'address' => 'Motong Road Motong, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.317852811,
                'longitude_point' => 123.2891322,
                'tel_no' => '(035) 4210765',
                'e_mail_address' => 'estrelladokhonny@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Metals and Engineering',
                'course_registered_program' => 'Shielded Metal Arc Welding (SMAW) NC I - Mobile Training Program',
                'pgf_level' => 'NC I',
                'duration' => '268 Hours',
                'program_reg_no' => 'WTR No. MTP-202307MEEEAW103-113',
                'date_issued' => '2024-05-31 00:00:00',
                'expiration_date' => '2029-06-01 00:00:00',
                'trainer' => "Imelda R. Ubag\nEduardo P. Mondarte\nIsagani B. Abril\nJungie A. Helardes\nGermano A. Jabanes\nEdgardo A. Zamora\nJosie Wen A. Lejarso\nJimmy L. Oyangorin",
                'nttc' => "NTTC No. 221707461200070\nNTTC No. 221807461200547\nNTTC No. 221807461200422\nNTTC No. 201907461200300\nNTTC No. 221807461200424\nNTTC No. 212107461200073\nNTTC No. 221807461200453\nNTTC No. 232207461200047",
                'expiration_date_of_nttc' => "2026-11-04\n2027-10-11\n2027-08-04\n2024-12-15\n2027-03-30\n2024-03-04\n2025-01-27\n2028-01-30",
            ],
            // Row 8
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0031',
                'name_of_institution' => 'Global Tech Manpower Institute Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Eduardo P. Mondarte - Administrator',
                'address' => 'Motong Road Motong, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.317852811,
                'longitude_point' => 123.2891322,
                'tel_no' => '(035) 4210765',
                'e_mail_address' => 'estrelladokhonny@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Metals and Engineering',
                'course_registered_program' => 'Shielded Metal Arc Welding (SMAW) NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '268 Hours',
                'program_reg_no' => 'WTR No. MTP-202307MEEEAW206-114',
                'date_issued' => '2024-05-31 00:00:00',
                'expiration_date' => '2029-06-01 00:00:00',
                'trainer' => "Imelda R. Ubag\nEduardo P. Mondarte\nIsagani B. Abril\nJungie A. Helardes\nGermano A. Jabanes\nEdgardo A. Zamora\nJosie Wen A. Lejarso\nJimmy L. Oyangorin",
                'nttc' => "NTTC No. 221707461200070\nNTTC No. 221807461200547\nNTTC No. 221807461200422\nNTTC No. 201907461200300\nNTTC No. 221807461200424\nNTTC No. 212107461200073\nNTTC No. 221807461200453\nNTTC No. 232207461200047",
                'expiration_date_of_nttc' => "2026-11-04\n2027-10-11\n2027-08-04\n2024-12-15\n2027-03-30\n2024-03-04\n2025-01-27\n2028-01-30",
            ],
            // Row 9
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0021',
                'name_of_institution' => 'Teamskills Technological Institute, Inc.',
                'formerly_name_of_tvi' => "(Formerly: Teamskills School for Culinary Arts and Hopitality Management, Inc.)",
                'name_of_institution_s_head' => 'Ariel D. Ronato, D.B.A. - President/CEO',
                'address' => '3rd Floor, Cecilia Building, Capitol Area, North Road, Daro, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.30910084,
                'longitude_point' => 123.2911675,
                'tel_no' => "(035) 4226159 /\n09175535507 / 09989788731",
                'e_mail_address' => "info@team-skills.com\nteamskills.acenter@gmail.com",
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Tourism',
                'course_registered_program' => 'Bread and Pastry Production NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '141 Hours',
                'program_reg_no' => 'WTR No. MTP-202307TRSBPP209-115',
                'date_issued' => '2024-01-18 00:00:00',
                'expiration_date' => '2029-01-19 00:00:00',
                'trainer' => "Mishelle S. Chiong\nTina M. Ronato\nAriel D. Ronato\nNancy L. Acabodillo\nCrecenciana V. Batalan\nLigaya A. Morales\nAlex A. Pagohinog, Jr.\nCira Chel G. Kinkito\nRonalyn G. Turno\nEva A. Quiapo\nChona V. Morales",
                'nttc' => "NTTC No. 222207461200161\nNTTC No. 222207461200163",
                'expiration_date_of_nttc' => "2027-01-26\n2027-02-02",
            ],
            // Row 10
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0021',
                'name_of_institution' => 'Teamskills Technological Institute, Inc.',
                'formerly_name_of_tvi' => "(Formerly: Teamskills School for Culinary Arts and Hopitality Management, Inc.)",
                'name_of_institution_s_head' => 'Ariel D. Ronato, D.B.A. - President/CEO',
                'address' => '3rd Floor, Cecilia Building, Capitol Area, North Road, Daro, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.30910084,
                'longitude_point' => 123.2911675,
                'tel_no' => "(035) 4226159 /\n09175535507 / 09989788731",
                'e_mail_address' => "info@team-skills.com\nteamskills.acenter@gmail.com",
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Tourism',
                'course_registered_program' => 'Cookery NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '316 Hours',
                'program_reg_no' => 'WTR No. MTP-202307TRSCOK214-116',
                'date_issued' => '2024-01-18 00:00:00',
                'expiration_date' => '2029-01-19 00:00:00',
                'trainer' => "Alex A. Padohinog, Jr.\nMishelle S. Chiong\nLigaya A. Morales\nCrecenciana V. Batalan\nNancy L. Acabodillo\nTina M. Ronato\nAriel D. Ronato\nChona V. Morales\nJonelle Frias",
                'nttc' => 'Not indicated',
                'expiration_date_of_nttc' => 'Not indicated',
            ],
            // Row 11
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0021',
                'name_of_institution' => 'Teamskills Technological Institute, Inc.',
                'formerly_name_of_tvi' => "(Formerly: Teamskills School for Culinary Arts and Hopitality Management, Inc.)",
                'name_of_institution_s_head' => 'Ariel D. Ronato, D.B.A. - President/CEO',
                'address' => '3rd Floor, Cecilia Building, Capitol Area, North Road, Daro, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.30910084,
                'longitude_point' => 123.2911675,
                'tel_no' => "(035) 4226159 /\n09175535507 / 09989788731",
                'e_mail_address' => "info@team-skills.com\nteamskills.acenter@gmail.com",
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Tourism',
                'course_registered_program' => 'Housekeeping NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '436 Hours',
                'program_reg_no' => 'WTR No. MTP-202307TRSHSK213-117',
                'date_issued' => '2024-01-18 00:00:00',
                'expiration_date' => '2029-01-19 00:00:00',
                'trainer' => "Estella P. Maraña\nAriel D. Ronato",
                'nttc' => "NTTC No.: 221707461200009\nNTTC No.: 201907461200241",
                'expiration_date_of_nttc' => null,
            ],
            // Row 12
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0021',
                'name_of_institution' => 'Teamskills Technological Institute, Inc.',
                'formerly_name_of_tvi' => "(Formerly: Teamskills School for Culinary Arts and Hopitality Management, Inc.)",
                'name_of_institution_s_head' => 'Ariel D. Ronato, D.B.A. - President/CEO',
                'address' => '3rd Floor, Cecilia Building, Capitol Area, North Road, Daro, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.30910084,
                'longitude_point' => 123.2911675,
                'tel_no' => "(035) 4226159 /\n09175535507 / 09989788731",
                'e_mail_address' => "info@team-skills.com\nteamskills.acenter@gmail.com",
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Tourism',
                'course_registered_program' => 'Tourism Promotion Services NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '76 Hours',
                'program_reg_no' => 'WTR NO. MTP-202307TRSTPS215-118',
                'date_issued' => '2024-01-18 00:00:00',
                'expiration_date' => '2029-01-19 00:00:00',
                'trainer' => "Ariel D. Ronato\nFiona J. Lao",
                'nttc' => 'Not indicated',
                'expiration_date_of_nttc' => 'Not indicated',
            ],
            // Row 13
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0022',
                'name_of_institution' => 'Metro Dumaguete College Inc.',
                'formerly_name_of_tvi' => '(Formerly: FOUR WD COMPUTER TRAINING CENTER, INC.)',
                'name_of_institution_s_head' => 'Dr. Delma P. Manila, DPA, CESO V / President',
                'address' => 'E.J. Blanco Drive Extension, Brgy. Daro, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.31933516,
                'longitude_point' => 123.2912191,
                'tel_no' => '(035) 4229728 / 2259170 / 4226341 / 4224605 / 09177008455',
                'e_mail_address' => 'mdctechvoc@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Electrical and Electronics',
                'course_registered_program' => 'Computer Systems Servicing NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '280 Hours',
                'program_reg_no' => 'WTR No. MTP-202307ELCCSS213-109',
                'date_issued' => '2023-07-25 00:00:00',
                'expiration_date' => '2028-07-25 00:00:00',
                'trainer' => "Margielen P. Alcoreza\nRicky L. Baldado\nEdlyn P. Casal\nLindon A. Damaso\nApril Joy D. Palahang\nRoland R. Palallos",
                'nttc' => "NTTC No. 202007461200222\nNTTC No. 211707461200365\nNTTC No. 191807461200313\nNTTC No. 201707461200203\nNTTC No. 201907461200221\nNTTC No. 201707461200162",
                'expiration_date_of_nttc' => "2025-06-24\n2026-09-27\n2024-06-19\n2025-05-21\n2025-05-28\n2025-02-20",
            ],
            // Row 14
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0013',
                'name_of_institution' => 'Provincial Training Center - Dumaguete',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Jesila A. Ocariza - Center Administrator',
                'address' => 'Barangay Candau-ay, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.32125056,
                'longitude_point' => 123.2596064,
                'tel_no' => '(035) 422-9481',
                'e_mail_address' => 'ptc.dumaguete@tesda.gov.ph',
                'type_of_institution' => 'Public',
                'classification_of_institution' => 'TTI',
                'status' => 'WTR-MTP',
                'sector' => 'Automotive and Land Transportation',
                'course_registered_program' => 'Driving NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '118 Hours',
                'program_reg_no' => 'WTR No. MTP-202307ALTDRV204-127',
                'date_issued' => '2024-04-03 00:00:00',
                'expiration_date' => '2029-04-04 00:00:00',
                'trainer' => "Elvin Y. Baguio\nJerome A. Zamora\nRoskie A. Gabutero\nRey Jay E. Jacosalem\nEdlyn P. Casal",
                'nttc' => "NTTC No. 211907461200430\nNTTC No. 212007461200057\nNTTC No. 211907221200358\nNTTC No. 211907461200276\nNTTC No. 211807461200321",
                'expiration_date_of_nttc' => "2026-10-19\n2025-12-17\n2026-09-20\n2026-06-09\n2024-11-26",
            ],
            // Row 15
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0013',
                'name_of_institution' => 'Provincial Training Center - Dumaguete',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Jesila A. Ocariza - Center Administrator',
                'address' => 'Barangay Candau-ay, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.32125056,
                'longitude_point' => 123.2596064,
                'tel_no' => '(035) 422-9481',
                'e_mail_address' => 'ptc.dumaguete@tesda.gov.ph',
                'type_of_institution' => 'Public',
                'classification_of_institution' => 'TTI',
                'status' => 'WTR-MTP',
                'sector' => 'Construction',
                'course_registered_program' => 'Masonry NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '181 Hours',
                'program_reg_no' => 'WTR No. MTP-202307CONMAS218-128',
                'date_issued' => '2023-08-25 00:00:00',
                'expiration_date' => '2027-09-07 00:00:00',
                'trainer' => 'Elvin Y. Baguio',
                'nttc' => 'NTTC No. 191907461200291',
                'expiration_date_of_nttc' => '2024-06-13',
            ],
            // Row 16
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0013',
                'name_of_institution' => 'Provincial Training Center - Dumaguete',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Jesila A. Ocariza - Center Administrator',
                'address' => 'Barangay Candau-ay, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.32125056,
                'longitude_point' => 123.2596064,
                'tel_no' => '(035) 422-9481',
                'e_mail_address' => 'ptc.dumaguete@tesda.gov.ph',
                'type_of_institution' => 'Public',
                'classification_of_institution' => 'TTI',
                'status' => 'WTR-MTP',
                'sector' => 'Construction',
                'course_registered_program' => 'Tile Setting NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '117 Hours',
                'program_reg_no' => 'WTR No. MTP-202307CONTIL218-129',
                'date_issued' => '2023-08-25 00:00:00',
                'expiration_date' => '2027-09-07 00:00:00',
                'trainer' => 'Elvin Y. Baguio',
                'nttc' => 'NTTC No. 191907461200293',
                'expiration_date_of_nttc' => '2024-06-13',
            ],
            // Row 17
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0013',
                'name_of_institution' => 'Provincial Training Center - Dumaguete',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Jesila A. Ocariza - Center Administrator',
                'address' => 'Barangay Candau-ay, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.32125056,
                'longitude_point' => 123.2596064,
                'tel_no' => '(035) 422-9481',
                'e_mail_address' => 'ptc.dumaguete@tesda.gov.ph',
                'type_of_institution' => 'Public',
                'classification_of_institution' => 'TTI',
                'status' => 'WTR-MTP',
                'sector' => 'Agriculture, Forestry and Fishery',
                'course_registered_program' => 'Agroentrepreneurship NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '239 Hours',
                'program_reg_no' => 'WTR No. MTP-202307AFFAGE217-148',
                'date_issued' => '2024-04-03 00:00:00',
                'expiration_date' => '2029-04-04 00:00:00',
                'trainer' => "Beth Aimee D. Tubog\nEmmalyn B. Carreon\nMa. Evelyn A. Tuisa\nGladys T. Deleña\nRoberto P. Silva",
                'nttc' => "NTTC No. 191807461200412\nNTTC No. 221707461200239\nPTTC No. 2207460200005\nPTTC No. 2207460200006\nPTTC No. 2207460200011",
                'expiration_date_of_nttc' => "2024-09-12\n2026-10-15\n2024-06-23\n2024-06-23\n2024-09-26",
            ],
            // Row 18
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0011',
                'name_of_institution' => 'Sto. Niño Skills Training & Assessment Center Incorporated',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Joel S. Vidal / President',
                'address' => '206 West Rovira Road Pulantubig Dumaguete City Negros Oriental 6200',
                'latitude_point' => 9.326378153,
                'longitude_point' => 123.2970677,
                'tel_no' => '(035) 422-8378 / 09063135543',
                'e_mail_address' => 'stoninotrainingandassessment@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Social, Community Development and Other Services',
                'course_registered_program' => 'Bookkeeping NC III - Mobile Training Program',
                'pgf_level' => 'NC III',
                'duration' => '292 Hours',
                'program_reg_no' => 'WTR No. MTP-202307SOCBKP307-162',
                'date_issued' => '2023-12-27 00:00:00',
                'expiration_date' => '2028-08-10 00:00:00',
                'trainer' => 'Richie B. Bungart',
                'nttc' => 'NTTC No. 232307461300112',
                'expiration_date_of_nttc' => '2025-01-25',
            ],
            // Row 19
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0011',
                'name_of_institution' => 'Sto. Niño Skills Training & Assessment Center Incorporated',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Joel S. Vidal II / President',
                'address' => '206 West Rovira Road Pulantubig Dumaguete City Negros Oriental 6200',
                'latitude_point' => 9.326378153,
                'longitude_point' => 123.2970677,
                'tel_no' => '(035) 422-8378 / 09063135543',
                'e_mail_address' => null,
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Automotive and Land Transportation',
                'course_registered_program' => 'Driving NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '118 Hours',
                'program_reg_no' => 'WTR No. MTP-202407ALTDRV204-010',
                'date_issued' => '2024-01-26 00:00:00',
                'expiration_date' => '2028-08-10 00:00:00',
                'trainer' => 'Jerome A. Zamora',
                'nttc' => 'NTTC No. 212007461200057',
                'expiration_date_of_nttc' => '2025-12-17',
            ],
            // Row 20
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0009',
                'name_of_institution' => 'Silliman University',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Betty Cernol-McCann, Ph.D., Rpsy, CSSP / President',
                'address' => 'Dumaguete City, Negros Oriental',
                'latitude_point' => 9.311966863,
                'longitude_point' => 123.3073819,
                'tel_no' => '(035) 422-6002',
                'e_mail_address' => null,
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'HEI',
                'status' => 'WTR-MTP',
                'sector' => 'Agriculture, Forestry and Fishery',
                'course_registered_program' => 'Animal Production (Poultry-Chicken) NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '226 Hours',
                'program_reg_no' => 'WTR No. MTP-202407AFFAPP213-020',
                'date_issued' => '2024-03-22 00:00:00',
                'expiration_date' => '2029-01-19 00:00:00',
                'trainer' => 'John Albert Branzuela Ungson',
                'nttc' => 'NTTC No. 241907461200079',
                'expiration_date_of_nttc' => '2028-12-17',
            ],
            // Row 21
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0009',
                'name_of_institution' => 'Silliman University',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Betty Cernol-McCann, Ph.D., Rpsy, CSSP / President',
                'address' => 'Dumaguete City, Negros Oriental',
                'latitude_point' => 9.311966863,
                'longitude_point' => 123.3073819,
                'tel_no' => '(035) 422-6002',
                'e_mail_address' => null,
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'HEI',
                'status' => 'WTR-MTP',
                'sector' => 'Agriculture, Forestry and Fishery',
                'course_registered_program' => 'Animal Production (Swine) NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '306 Hours',
                'program_reg_no' => 'WTR No. MTP-202407AFFAPS213-021',
                'date_issued' => '2024-03-22 00:00:00',
                'expiration_date' => '2029-01-19 00:00:00',
                'trainer' => 'Justin Philip Ginggoyon Valencia',
                'nttc' => 'NTTC No. 231907461200508',
                'expiration_date_of_nttc' => '2028-08-31',
            ],
            // Row 22
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0009',
                'name_of_institution' => 'Silliman University',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Betty Cernol-McCann, Ph.D., Rpsy, CSSP / President',
                'address' => 'Dumaguete City, Negros Oriental',
                'latitude_point' => 9.311966863,
                'longitude_point' => 123.3073819,
                'tel_no' => '(035) 422-6002',
                'e_mail_address' => 'tevec@su.edu.ph and blanchiemutzurrum@su.edu.ph',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'HEI',
                'status' => 'WTR-MTP',
                'sector' => 'Agriculture, Forestry and Fishery',
                'course_registered_program' => 'Organic Agriculture Production NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '232 Hours',
                'program_reg_no' => 'WTR No. MTP-202407AFFOAP212-023',
                'date_issued' => '2024-04-11 00:00:00',
                'expiration_date' => '2028-08-03 00:00:00',
                'trainer' => 'Dorcas S. Panangganan',
                'nttc' => 'NTTC No. 211707461200460',
                'expiration_date_of_nttc' => '2026-08-11',
            ],
            // Row 23
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '1st',
                'municipality' => 'Guihulngan City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0016',
                'name_of_institution' => 'ZN Global Knowledge and Skills, Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Jesamyl D. Velasco - President',
                'address' => 'S. Villegas St., Poblacion, Guihulngan City, Negros Oriental',
                'latitude_point' => 10.11793882,
                'longitude_point' => 123.2696412,
                'tel_no' => "09971879449 /\n09198985063",
                'e_mail_address' => 'znglobal.guihulngan@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Human Health/ Health Care',
                'course_registered_program' => 'Hilot (Wellness Massage) NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '120 Hours',
                'program_reg_no' => 'WTR No. MTP-202407HHCHIL208-024',
                'date_issued' => '2024-04-23 00:00:00',
                'expiration_date' => '2029-02-16 00:00:00',
                'trainer' => 'Rodelo T. Cabilin',
                'nttc' => 'NTTC No. 201909721200116',
                'expiration_date_of_nttc' => '2025-02-03',
            ],
            // Row 24
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0021',
                'name_of_institution' => 'Teamskills Technological Institute, Inc.',
                'formerly_name_of_tvi' => '(Formerly: Teamskills School for Culinary Arts and Hospitality Management, Inc.)',
                'name_of_institution_s_head' => 'Ariel D. Ronato, D.B.A. - President/CEO',
                'address' => '3rd Floor, Cecilia Building, Capitol Area, North Road, Daro, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.314098122,
                'longitude_point' => 123.3034628,
                'tel_no' => "(035) 4226159 /\n09175535507 / 09989788731",
                'e_mail_address' => "info@team-skills.com\nteamskills.acenter@gmail.com",
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Tourism',
                'course_registered_program' => 'Barista NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '178 Hours',
                'program_reg_no' => 'WTR No. MTP-202407TRSBRT213-029',
                'date_issued' => '2024-06-06 00:00:00',
                'expiration_date' => '2029-01-19 00:00:00',
                'trainer' => "Ariel C. Ronato\nTina M. Ronato\nElrey Elmoore C. Abella\nAngelo S. Salvoro",
                'nttc' => "NTTC No. 221907461200032\nNTTC No. 222207461200165\nNTTC No. 232107461200262\nNTTC No. 232307461200554",
                'expiration_date_of_nttc' => "2027-01-09\n2027-02-02\n2027-09-25\n2028-06-04",
            ],
            // Row 25
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0030',
                'name_of_institution' => 'Philippine Call Center Institute Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Kristelle Lynne P. Ong, Center Manager',
                'address' => '2/F, Doña Milagros Bldg., Sta. Rosa St., Dumaguete City, Negros Oriental',
                'latitude_point' => 9.30403785,
                'longitude_point' => 123.3078172,
                'tel_no' => '035-4210834, 09362125218, 09088123684',
                'e_mail_address' => 'kristelleong@yahoo.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Information and Communication Technology',
                'course_registered_program' => 'Contact Center Services NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '144 Hours',
                'program_reg_no' => 'WTR No. MTP-202407ICTCCS214-045',
                'date_issued' => '2024-10-24 00:00:00',
                'expiration_date' => '2029-03-18 00:00:00',
                'trainer' => "Jelo R. Silvano\nLudy Mae G. Bulahan\nLuchie B. Stemper,\nBuena Asuncion D. San Marte,\nDoinita C. Bensing,\nAdell T. Pacudan",
                'nttc' => 'Not indicated',
                'expiration_date_of_nttc' => 'Not indicated',
            ],
            // Row 26
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0022',
                'name_of_institution' => 'Metro Dumaguete College Inc.',
                'formerly_name_of_tvi' => '(Formerly: FOUR WD COMPUTER TRAINING CENTER, INC.)',
                'name_of_institution_s_head' => 'Dr. Delma P. Manila, DPA, CESO V / President',
                'address' => 'E.J. Blanco Drive Extension, Brgy. Daro, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.31933516,
                'longitude_point' => 123.2912191,
                'tel_no' => '(035) 4229728 / 2259170 / 4226341 / 4224605 / 09177008455',
                'e_mail_address' => 'mdctechvoc@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Tourism',
                'course_registered_program' => 'Bread and Pastry Production NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '141 Hours',
                'program_reg_no' => 'WTR No. MTP-202407TRSBPP209-048',
                'date_issued' => '2024-11-19 00:00:00',
                'expiration_date' => '2029-01-19 00:00:00',
                'trainer' => 'Margielen P. Alcoreza',
                'nttc' => 'NTTC No. 202007461200343',
                'expiration_date_of_nttc' => '2025-06-24',
            ],
            // Row 27
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0022',
                'name_of_institution' => 'Metro Dumaguete College Inc.',
                'formerly_name_of_tvi' => '(Formerly: FOUR WD COMPUTER TRAINING CENTER, INC.)',
                'name_of_institution_s_head' => 'Dr. Delma P. Manila, DPA, CESO V / President',
                'address' => 'E.J. Blanco Drive Extension, Brgy. Daro, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.31933516,
                'longitude_point' => 123.2912191,
                'tel_no' => '(035) 4229728 / 2259170 / 4226341 / 4224605 / 09177008455',
                'e_mail_address' => 'mdctechvoc@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'TVET',
                'course_registered_program' => 'Trainers Methodology Level I (Trainer/Assessor) - Mobile Training Program',
                'pgf_level' => 'Level I',
                'duration' => '264 Hours',
                'program_reg_no' => 'WTR No. MTP-202407TVETRM111-049',
                'date_issued' => '2024-11-19 00:00:00',
                'expiration_date' => '2028-08-02 00:00:00',
                'trainer' => "Margielen P. Alcoreza\nEmmalyn B. Carreon\nEdlyn P. Casal",
                'nttc' => "TMC No. 20074601000019\nTMC No. 23074601000012\nTMC No. 23074601012100",
                'expiration_date_of_nttc' => "2025-07-01\n2028-02-19\n2028-06-01",
            ],
            // Row 28
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0022',
                'name_of_institution' => 'Metro Dumaguete College Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Dr. Delma P. Manila, DPA, CESO V / President',
                'address' => 'E.J. Blanco Drive Extension, Brgy. Daro, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.31933516,
                'longitude_point' => 123.2912191,
                'tel_no' => '(035) 4229728 / 2259170 / 4226341 / 4224605 / 09177008455',
                'e_mail_address' => 'mdctechvoc@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Tourism',
                'course_registered_program' => 'Bread and Pastry Production NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '141 Hours',
                'program_reg_no' => 'WTR No. MTP-202407TRSBPP209-050',
                'date_issued' => '2024-11-27 00:00:00',
                'expiration_date' => '2029-01-19 00:00:00',
                'trainer' => "Margielen P. Alcoreza\nBaby Jean S. Baligasa\nGina A. Ronidna",
                'nttc' => "NTTC No. 202007461200343\nNTTC No. 221807461200501\nNTTC No. 221707461200014",
                'expiration_date_of_nttc' => "2025-06-24\n2027-10-06\n2026-05-30",
            ],
            // Row 29
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0022',
                'name_of_institution' => 'Metro Dumaguete College Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Dr. Delma P. Manila, DPA, CESO V / President',
                'address' => 'E.J. Blanco Drive Extension, Brgy. Daro, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.31933516,
                'longitude_point' => 123.2912191,
                'tel_no' => '(035) 4229728 / 2259170 / 4226341 / 4224605 / 09177008455',
                'e_mail_address' => 'mdctechvoc@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Social, Community Development and Other Services',
                'course_registered_program' => 'Bookkeeping NC III - Mobile Training Program',
                'pgf_level' => 'NC III',
                'duration' => '438 Hours',
                'program_reg_no' => 'WTR No. MTP-202407SOCBKP307-051',
                'date_issued' => '2024-11-27 00:00:00',
                'expiration_date' => '2029-05-27 00:00:00',
                'trainer' => 'Delma P. Manila',
                'nttc' => 'NTTC No. 242207461300083',
                'expiration_date_of_nttc' => '2028-06-06',
            ],
            // Row 30
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0013',
                'name_of_institution' => 'Provincial Training Center - Dumaguete',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Jesila A. Ocariza - Center Administrator',
                'address' => 'Barangay Candau-ay, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.32125056,
                'longitude_point' => 123.2596064,
                'tel_no' => '(035) 422-9481',
                'e_mail_address' => 'ptc.dumaguete@tesda.gov.ph',
                'type_of_institution' => 'Public',
                'classification_of_institution' => 'TTI',
                'status' => 'WTR-MTP',
                'sector' => 'TVET',
                'course_registered_program' => 'Trainers Methodology Level I (Trainer/Assessor) - Mobile Training Program',
                'pgf_level' => 'Level I',
                'duration' => '364 Hours',
                'program_reg_no' => 'WTR No. MTP-202407TVETRM111-052',
                'date_issued' => '2024-12-02 00:00:00',
                'expiration_date' => '2027-09-07 00:00:00',
                'trainer' => "Margielen P. Alcoreza\nEmmalyn B. Carreon\nEdlyn P. Casal",
                'nttc' => "TMC No. 20074601000019\nTMC No. 23074601000012\nTMC No. 23074601012100",
                'expiration_date_of_nttc' => "2025-06-24\n2028-02-19\n2028-06-01",
            ],
            // Row 31
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0011',
                'name_of_institution' => 'Sto. Niño Skills Training & Assessment Center Incorporated',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Annabelle C. Vidal, School Administrator',
                'address' => '206 West Rovira Road Pulantubig Dumaguete City Negros Oriental 6200',
                'latitude_point' => 9.326378153,
                'longitude_point' => 123.2970677,
                'tel_no' => '(035) 422-8378 / 09063135543',
                'e_mail_address' => 'stoninotrainingandassessment@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Human Health/ Health Care',
                'course_registered_program' => 'Caregiving NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '786 Hours',
                'program_reg_no' => 'WTR No. MTP-202507HHCCGV207-003',
                'date_issued' => '2025-01-17 00:00:00',
                'expiration_date' => '2028-08-10 00:00:00',
                'trainer' => 'Jurez Lilybeth Z. Fernandez',
                'nttc' => 'NTTC No. 242207461200717',
                'expiration_date_of_nttc' => '2029-02-28',
            ],
            // Row 32
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '1st',
                'municipality' => 'Guihulngan City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0004',
                'name_of_institution' => 'Guihulngan Satellite Skills Development Center',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Roberto T. Bustamante, Executive Director',
                'address' => 'Public Market, Guihulngan City, Negros Oriental',
                'latitude_point' => 10.13170829,
                'longitude_point' => 123.2733288,
                'tel_no' => '(035) 3361440/ 410-3098',
                'e_mail_address' => 'gssdc.guihulngan@yahoo.com',
                'type_of_institution' => 'Public',
                'classification_of_institution' => 'LGU',
                'status' => 'WTR-MTP',
                'sector' => 'Garments',
                'course_registered_program' => 'Dressmaking NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '275 Hours',
                'program_reg_no' => 'WTR No. MTP-202507GRMDRM205-016',
                'date_issued' => '2025-05-26 00:00:00',
                'expiration_date' => '2029-02-28 00:00:00',
                'trainer' => 'Michelle S. Montemayor',
                'nttc' => 'NTTC No. 221807461200480',
                'expiration_date_of_nttc' => '2027-02-09',
            ],
            // Row 33
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Bais City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0035',
                'name_of_institution' => 'Rams Art Training and Assessment Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Ramon E. Calumpang',
                'address' => 'Km 50, National Highway (Near DPWH Weighbridge) Brgy. Tamisu, Bais City, Negros Oriental',
                'latitude_point' => 9.629917044,
                'longitude_point' => 123.097848,
                'tel_no' => '(035) 4029837',
                'e_mail_address' => 'ramsartbais@gamil.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Tourism',
                'course_registered_program' => 'Bread and Pastry Production NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '141 Hours',
                'program_reg_no' => 'WTR No. MTP-2025-07-46-TRSBPP209-027',
                'date_issued' => '2025-09-29 00:00:00',
                'expiration_date' => '2029-03-18 00:00:00',
                'trainer' => "Agnes M. Niere\nJudelyn P. Rebutazo",
                'nttc' => "NTTC No. 232307461200334\nNTTC No. 252407461200078",
                'expiration_date_of_nttc' => "2028-05-25\n2029-03-12",
            ],
            // Row 34
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Bais City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0035',
                'name_of_institution' => 'Rams Art Training and Assessment Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Ramon E. Calumpang',
                'address' => 'Km 50, National Highway (Near DPWH Weighbridge) Brgy. Tamisu, Bais City, Negros Oriental',
                'latitude_point' => 9.629917044,
                'longitude_point' => 123.097848,
                'tel_no' => '(035) 4029837',
                'e_mail_address' => 'ramsartbais@gamil.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Social, Community Development and Other Services',
                'course_registered_program' => 'Bookkeeping NC III - Mobile Training Program',
                'pgf_level' => 'NC III',
                'duration' => '438 Hours',
                'program_reg_no' => 'WTR No. MTP-2025-07-46-SOCBKP307-028',
                'date_issued' => '2025-09-29 00:00:00',
                'expiration_date' => '2029-11-16 00:00:00',
                'trainer' => 'Joan A. Amposta',
                'nttc' => 'NTTC No. 242407461300637',
                'expiration_date_of_nttc' => '2029-07-27',
            ],
            // Row 35
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Bais City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0035',
                'name_of_institution' => 'Rams Art Training and Assessment Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Ramon E. Calumpang',
                'address' => 'Km 50, National Highway (Near DPWH Weighbridge) Brgy. Tamisu, Bais City, Negros Oriental',
                'latitude_point' => 9.629917044,
                'longitude_point' => 123.097848,
                'tel_no' => '(035) 4029837',
                'e_mail_address' => 'ramsartbais@gamil.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Electrical and Electronics',
                'course_registered_program' => 'Electrical Installation and Maintenance NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '196 Hours',
                'program_reg_no' => 'WTR No. MTP-2025-07-46-ELCEIM215-029',
                'date_issued' => '2025-09-29 00:00:00',
                'expiration_date' => '2029-09-26 00:00:00',
                'trainer' => "Francis E. Cadallo\nRamon E. Calumpang",
                'nttc' => "NTTC No. 242107461200311\nNTTC No. 232307461200265",
                'expiration_date_of_nttc' => "2029-03-19\n2027-12-02",
            ],
            // Row 36
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Bayawan City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => 'Not Found',
                'name_of_institution' => 'Integrated Development Training and Assessment Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Elma C. Tanasan, President',
                'address' => 'Sitio Buli Buli Banga, City of Bayawan (Tulong), Negros Oriental, Region VII (Central Visayas), 6221',
                'latitude_point' => 9.388800738,
                'longitude_point' => 122.7956269,
                'tel_no' => '0916-763-2822',
                'e_mail_address' => 'atstaci2023@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Agriculture, Forestry and Fishery',
                'course_registered_program' => 'Agroentrepreneurship NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '239 Hours',
                'program_reg_no' => 'WTR No. MTP 2025-07-46-AFFAGE217-032',
                'date_issued' => '2025-11-07 00:00:00',
                'expiration_date' => '2029-12-14 00:00:00',
                'trainer' => 'Kenneth John Baliquig',
                'nttc' => 'NTTC No. 242407461200405',
                'expiration_date_of_nttc' => '2029-05-30',
            ],
            // Row 37
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Bayawan City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => 'Not Found',
                'name_of_institution' => 'Integrated Development Training and Assessment Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Elma C. Tanasan, President',
                'address' => 'Sitio Buli Buli Banga, City of Bayawan (Tulong), Negros Oriental, Region VII (Central Visayas), 6221',
                'latitude_point' => 9.388800738,
                'longitude_point' => 122.7956269,
                'tel_no' => '0916-763-2822',
                'e_mail_address' => 'atstaci2023@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Social, Community Development and Other Services',
                'course_registered_program' => 'Bookkeeping NC III - Mobile Training Program',
                'pgf_level' => 'NC III',
                'duration' => '292 Hours',
                'program_reg_no' => 'WTR No. MTP 2025-07-46-SOCBKP307-033',
                'date_issued' => '2025-11-07 00:00:00',
                'expiration_date' => '2029-12-14 00:00:00',
                'trainer' => 'Kenneth John Baliquig',
                'nttc' => 'NTTC No. 242407461300402',
                'expiration_date_of_nttc' => '2027-03-11',
            ],
            // Row 38
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Bayawan City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => 'Not Found',
                'name_of_institution' => 'Integrated Development Training and Assessment Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Elma C. Tanasan, President',
                'address' => 'Sitio Buli Buli Banga, City of Bayawan (Tulong), Negros Oriental, Region VII (Central Visayas), 6221',
                'latitude_point' => 9.388800738,
                'longitude_point' => 122.7956269,
                'tel_no' => '0916-763-2822',
                'e_mail_address' => 'atstaci2023@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Automotive and Land Transportation',
                'course_registered_program' => 'Driving NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '118 Hours',
                'program_reg_no' => 'WTR No. MTP 2025-07-46-ALTDRV204-034',
                'date_issued' => '2025-11-07 00:00:00',
                'expiration_date' => '2029-12-14 00:00:00',
                'trainer' => 'Kenneth John Baliquig',
                'nttc' => 'NTTC No. 242407461200403',
                'expiration_date_of_nttc' => '2027-09-02',
            ],
            // Row 39
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '3rd',
                'municipality' => 'Bayawan City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0002',
                'name_of_institution' => 'Southern Tech College Foundation Incorporated',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Ion Joseph T. Bollos, MSEM - President',
                'address' => 'National Highway, Villareal, Bayawan City, Negros Oriental',
                'latitude_point' => 9.359063707,
                'longitude_point' => 122.8214852,
                'tel_no' => '(035) 531-0879',
                'e_mail_address' => 'southerntechcollegebayawan@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Social, Community Development and Other Services',
                'course_registered_program' => 'Bookkeeping NC III - Mobile Training Program',
                'pgf_level' => 'NC III',
                'duration' => '292 Hours',
                'program_reg_no' => 'WTR No. MTP 2025-07-46-SOCBKP307-039',
                'date_issued' => '2025-12-10 00:00:00',
                'expiration_date' => '2028-12-12 00:00:00',
                'trainer' => 'Rosemarie O. Guardiano',
                'nttc' => 'NTTC No. 231907461300246',
                'expiration_date_of_nttc' => '2028-12-04',
            ],
            // Row 40
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '3rd',
                'municipality' => 'Bayawan City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0002',
                'name_of_institution' => 'Southern Tech College Foundation Incorporated',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Ion Joseph T. Bollos, MSEM - President',
                'address' => 'National Highway, Villareal, Bayawan City, Negros Oriental',
                'latitude_point' => 9.359063707,
                'longitude_point' => 122.8214852,
                'tel_no' => '(035) 531-0879',
                'e_mail_address' => 'southerntechcollegebayawan@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Electrical and Electronics',
                'course_registered_program' => 'Computer Systems Servicing NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '280 Hours',
                'program_reg_no' => 'WTR No. MTP 2025-07-46-ELCCSS213-040',
                'date_issued' => '2025-12-10 00:00:00',
                'expiration_date' => '2028-12-12 00:00:00',
                'trainer' => 'Julie Mae J. Librado',
                'nttc' => 'NTTC No. 242207461200690',
                'expiration_date_of_nttc' => '2029-08-29',
            ],
            // Row 41
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0011',
                'name_of_institution' => 'Sto. Niño Skills Training & Assessment Center Incorporated',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Annabelle C. Vidal, Administrator',
                'address' => '206 West Rovira Road Pulantubig Dumaguete City Negros Oriental 6200',
                'latitude_point' => 9.326396272,
                'longitude_point' => 123.2970941,
                'tel_no' => '(035) 422-8378 / 09063135543',
                'e_mail_address' => 'stoninotrainingandassessment@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Agriculture, Forestry and Fishery',
                'course_registered_program' => 'Agroentrepreneurship NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '239 Hours',
                'program_reg_no' => 'WTR No. MTP 2025-07-46-AFFAGE217-041',
                'date_issued' => '2025-12-10 00:00:00',
                'expiration_date' => '2025-12-17 00:00:00',
                'trainer' => "Richie B. Bungart\nJudith D. Baguio\nRogir B. Agir",
                'nttc' => "NTTC No. 221707461200186\nNTTC No. 242307461200489\nNTTC No. 242007461200627",
                'expiration_date_of_nttc' => "2026-10-16\n2028-12-22\n2029-08-30",
            ],
            // Row 42
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Dumaguete City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0021',
                'name_of_institution' => 'Teamskills Technological Institute, Inc.',
                'formerly_name_of_tvi' => "(Formerly: Teamskills School for Culinary Arts and Hopitality Management, Inc.)",
                'name_of_institution_s_head' => 'Ariel D. Ronato, D.B.A. - President/CEO',
                'address' => '3rd Floor, Cecilia Building, Capitol Area, North Road, Daro, Dumaguete City, Negros Oriental',
                'latitude_point' => 9.30910084,
                'longitude_point' => 123.2911675,
                'tel_no' => "(035) 4226159 /\n09175535507 / 09989788731",
                'e_mail_address' => "info@team-skills.com\nteamskills.acenter@gmail.com",
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'TVET',
                'course_registered_program' => 'Trainers Methodology Level I (Trainer/Assessor) - Mobile Training Program',
                'pgf_level' => 'Level I',
                'duration' => '264 Hours',
                'program_reg_no' => 'WTR No. MTP 2025-07-46-TVETRM111-042',
                'date_issued' => '2025-12-10 00:00:00',
                'expiration_date' => '2027-10-16 00:00:00',
                'trainer' => "Ariel D. Ronato\nFloridel C. Pelin\nLuz L. Borromeo\nRowell L. Panuncial\nMark Alexander A. Reposo\nElrey Elmoore C. Abella",
                'nttc' => "TMC25074601000058\nTMC-23071201010768\nTMC-23072201000616\nTMC23072201001009\nTMC-21074601000019\nTMC-21074601000007",
                'expiration_date_of_nttc' => "2030-01-08\n2028-11-20\n2028-02-21\n2028-04-11\n2026-09-20\n2026-02-10",
            ],
            // Row 43
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Bayawan City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => 'Not Found',
                'name_of_institution' => 'Armstrong Career and Technical Education Institute Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Larry Neil C. Abalajon, President',
                'address' => 'Brgy. Kalumboyan, Bayawan City, Negros Oriental, 6221',
                'latitude_point' => 9.51076,
                'longitude_point' => 122.80732,
                'tel_no' => '0997-067-5423 / 0922-770-6451',
                'e_mail_address' => 'actei.edu1118@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Agriculture, Forestry and Fishery',
                'course_registered_program' => 'Organic Agriculture Production NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '232 Hours',
                'program_reg_no' => 'WTR No. MTP 202507AFFOAP212-052',
                'date_issued' => '2025-12-26 00:00:00',
                'expiration_date' => '2029-02-23 00:00:00',
                'trainer' => "Greg A. Cadapan\nAllan Eugine Q. Lagradilla\nMichel Padpad\nFrancis B. Betchido\nDereck James M. Requina",
                'nttc' => "NTTC No. 231907461200333\nNTTC No. 222007611200151\nNTTC No. 232207461200392\nNTTC No. 221907461200228\nNTTC No. 221807461200551",
                'expiration_date_of_nttc' => "2028-06-14\n2027-02-21\n2028-04-28\n2027-03-18\n2027-09-06",
            ],
            // Row 44
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Bais City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0012',
                'name_of_institution' => 'Abellana Technical and Vocational Center, Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Fe L. Abellana, President',
                'address' => 'Abellana\'s Building, Osmena Street , Brgy. 2 Bais City, Negros Oriental',
                'latitude_point' => 9.591613909,
                'longitude_point' => 123.1211719,
                'tel_no' => '(035) 5313732 / 4023717 / 09351633419',
                'e_mail_address' => 'abellanastechcenter@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Human Health/ Health Care',
                'course_registered_program' => 'Hilot (Wellness Massage) NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '120 Hours',
                'program_reg_no' => 'WTR No. MTP 202607HHCHIL208-006',
                'date_issued' => '2026-03-04 00:00:00',
                'expiration_date' => '2029-04-03 00:00:00',
                'trainer' => 'Fe L. Abellana',
                'nttc' => 'NTTC No. 18074601000185',
                'expiration_date_of_nttc' => '2026-10-24',
            ],
            // Row 45
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Bais City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0012',
                'name_of_institution' => 'Abellana Technical and Vocational Center, Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Fe L. Abellana, President',
                'address' => 'Abellana\'s Building, Osmena Street , Brgy. 2 Bais City, Negros Oriental',
                'latitude_point' => 9.591613909,
                'longitude_point' => 123.1211719,
                'tel_no' => '(035) 5313732 / 4023717 / 09351633419',
                'e_mail_address' => 'abellanastechcenter@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Human Health/ Health Care',
                'course_registered_program' => 'Hilot (Wellness Massage) NC II - Mobile Training Program',
                'pgf_level' => 'NC II',
                'duration' => '120 Hours',
                'program_reg_no' => 'WTR No. MTP 202607HHCHIL208-007',
                'date_issued' => '2026-03-04 00:00:00',
                'expiration_date' => '2029-04-03 00:00:00',
                'trainer' => 'Monica R. Atay',
                'nttc' => 'NTTC No. 252209721200298',
                'expiration_date_of_nttc' => '2030-06-22',
            ],
            // Row 46
            [
                'region' => 'VII',
                'province' => 'Negros Oriental',
                'congressional_district' => '2nd',
                'municipality' => 'Bais City',
                'municipality_class' => 'Component',
                'unique_institution_identification' => '0746-0012',
                'name_of_institution' => 'Abellana Technical and Vocational Center, Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Fe L. Abellana, President',
                'address' => 'Abellana\'s Building, Osmena Street , Brgy. 2 Bais City, Negros Oriental',
                'latitude_point' => 9.591613909,
                'longitude_point' => 123.1211719,
                'tel_no' => '(035) 5313732 / 4023717 / 09351633419',
                'e_mail_address' => 'abellanastechcenter@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR-MTP',
                'sector' => 'Social, Community Development and Other Services',
                'course_registered_program' => 'Bookkeeping NC III - Mobile Training Program',
                'pgf_level' => 'NC III',
                'duration' => '292 Hours',
                'program_reg_no' => 'WTR No. MTP 202607SOCBKP307-008',
                'date_issued' => '2026-03-04 00:00:00',
                'expiration_date' => '2029-04-03 00:00:00',
                'trainer' => 'Ryan Cris M. Alabo',
                'nttc' => 'NTTC No. 242407461300485',
                'expiration_date_of_nttc' => '2028-12-22',
            ],

            [
                'region' => 'VII',
                'province' => 'Siquijor',
                'congressional_district' => 'Lone',
                'municipality' => 'Siquijor',
                'municipality_class' => '4th',
                'unique_institution_identification' => 'Not Found',
                'name_of_institution' => 'Carmelite College of Siquijor, Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Sr. Mila Margaret V. Motegrejo',
                'address' => 'Balasbalas, Cang-Alwang, Tinago, Siquijor, Siquijor',
                'latitude_point' => 9.213684924,
                'longitude_point' => 123.4803531,
                'tel_no' => '035-344-2098 / (035) 542-6276',
                'e_mail_address' => 'ccsi.official@carmelitecollegesiquijor.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR',
                'sector' => 'Electrical and Electronics',
                'course_registered_program' => 'Computer Systems Servicing NC II',
                'pgf_level' => 'NC II',
                'duration' => '360 hours',
                'program_reg_no' => '20220761ELCCSS213092',
                'date_issued' => '2024-04-19 00:00:00',
                'expiration_date' => '2029-04-22 00:00:00',
                'trainer' => 'Kenneth P. Llorente',
                'nttc' => '1.61408E+14',
                'expiration_date_of_nttc' => 'Not indicated',
            ],
            // Row 2
            [
                'region' => 'VII',
                'province' => 'Siquijor',
                'congressional_district' => 'Lone',
                'municipality' => 'Lazi',
                'municipality_class' => '4th',
                'unique_institution_identification' => 'Not Found',
                'name_of_institution' => 'PSP Technological Institute Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Pierre S. Pakilit',
                'address' => 'Pakilit Residence Alvarico Tigbawan (Pob.) Lazi, Siquijor, Region VII, Philippines 6228',
                'latitude_point' => 9.218691948,
                'longitude_point' => 123.5189104,
                'tel_no' => '0965-774-2490',
                'e_mail_address' => 'psptechnology2019@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR',
                'sector' => 'Automotive and Land Transportation',
                'course_registered_program' => 'Driving NC II',
                'pgf_level' => 'NC II',
                'duration' => '118 hours',
                'program_reg_no' => '20190761ALTDRV204103',
                'date_issued' => '2023-12-28 00:00:00',
                'expiration_date' => '2028-12-29 00:00:00',
                'trainer' => "Arnold M. Magtahas,\nOrlando J. Gio,\nExcel C. Cabanag",
                'nttc' => 'NTTC No. 191907611200444 No.181807461200398, No. 191507461200037',
                'expiration_date_of_nttc' => '08-Oct-23, Aug. 28, 2023, Oct. 16, 2023',
            ],
            // Row 3
            [
                'region' => 'VII',
                'province' => 'Siquijor',
                'congressional_district' => 'Lone',
                'municipality' => 'Lazi',
                'municipality_class' => '4th',
                'unique_institution_identification' => 'Not Found',
                'name_of_institution' => 'PSP Technological Institute Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Pierre S. Pakilit',
                'address' => 'Pakilit Residence Alvarico Tigbawan (Pob.) Lazi, Siquijor, Region VII, Philippines 6228',
                'latitude_point' => 9.218691948,
                'longitude_point' => 123.5189104,
                'tel_no' => '0965-774-2490',
                'e_mail_address' => 'psptechnology2019@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR',
                'sector' => 'Electrical and Electronics',
                'course_registered_program' => 'Electrical Installation and Maintenance NC II',
                'pgf_level' => 'NC II',
                'duration' => '244 Hours',
                'program_reg_no' => '20220761ELCEIM215069',
                'date_issued' => '2023-12-28 00:00:00',
                'expiration_date' => '2028-12-29 00:00:00',
                'trainer' => 'Huberto V. Duran',
                'nttc' => 'NTTC No.',
                'expiration_date_of_nttc' => 'February 15, 2027',
            ],
            // Row 4
            [
                'region' => 'VII',
                'province' => 'Siquijor',
                'congressional_district' => 'Lone',
                'municipality' => 'San Juan',
                'municipality_class' => '5th',
                'unique_institution_identification' => 'Not Found',
                'name_of_institution' => 'Siquijor Language Academy Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Frelyn L. Pagente, CEO',
                'address' => 'Maite, San Juan, Siquijor, Region VII (Central Visayas), 6227',
                'latitude_point' => 9.151831975,
                'longitude_point' => 123.5013812,
                'tel_no' => '9279707007',
                'e_mail_address' => 'frelynpagente@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'RTP',
                'sector' => 'Others (Languages)',
                'course_registered_program' => 'ESL Beginner Course',
                'pgf_level' => 'N/A',
                'duration' => '120 Hours',
                'program_reg_no' => 'NTR No. 202207610024',
                'date_issued' => '2022-11-22 00:00:00',
                'expiration_date' => '2027-11-21 00:00:00',
                'trainer' => "Jay Ann Amorsolo\nShiela Mae M. Caroro",
                'nttc' => 'TMC No. 22076101022381',
                'expiration_date_of_nttc' => 'Not indicated',
            ],
            // Row 5
            [
                'region' => 'VII',
                'province' => 'Siquijor',
                'congressional_district' => 'Lone',
                'municipality' => 'Larena',
                'municipality_class' => '5th',
                'unique_institution_identification' => 'Not Found',
                'name_of_institution' => 'CMC Institute of Business Management, Skills Training and Assessment Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Aida C. Madulara - President',
                'address' => 'North Poblacion, Larena, Siquijor',
                'latitude_point' => 9.278613093,
                'longitude_point' => 123.584607,
                'tel_no' => '9176710565',
                'e_mail_address' => 'madulara@yahoo.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR',
                'sector' => 'Tourism',
                'course_registered_program' => 'Events Management Services NC III',
                'pgf_level' => 'NC III',
                'duration' => '188 Hours',
                'program_reg_no' => 'WTR No. 20230761TRSEVM307006',
                'date_issued' => '2024-03-15 00:00:00',
                'expiration_date' => '2029-03-18 00:00:00',
                'trainer' => "Ana Liza A. Baluran\nJovie D. Cabais",
                'nttc' => "NTTC No. 211707121300387\nNTTC No. 191907121300496",
                'expiration_date_of_nttc' => "19-Sep-26\n5/24/2024",
            ],
            // Row 6
            [
                'region' => 'VII',
                'province' => 'Siquijor',
                'congressional_district' => 'Lone',
                'municipality' => 'Larena',
                'municipality_class' => '5th',
                'unique_institution_identification' => 'Not Found',
                'name_of_institution' => 'CMC Institute of Business Management, Skills Training and Assessment Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Aida C. Madulara - President',
                'address' => 'North Poblacion, Larena, Siquijor',
                'latitude_point' => 9.278613093,
                'longitude_point' => 123.584607,
                'tel_no' => '9176710565',
                'e_mail_address' => 'madulara@yahoo.com / cmcsiquijor.skillstraining@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR',
                'sector' => 'Tourism',
                'course_registered_program' => 'Food and Beverage Services NC II',
                'pgf_level' => 'NC II',
                'duration' => '436 Hours',
                'program_reg_no' => 'WTR No. 20230761TRSFBS213007',
                'date_issued' => '2024-03-15 00:00:00',
                'expiration_date' => '2029-03-18 00:00:00',
                'trainer' => 'Almarie M. Sumalpong',
                'nttc' => 'NTTC No. 211807611200303',
                'expiration_date_of_nttc' => '06/06/2026',
            ],
            // Row 7
            [
                'region' => 'VII',
                'province' => 'Siquijor',
                'congressional_district' => 'Lone',
                'municipality' => 'Larena',
                'municipality_class' => '5th',
                'unique_institution_identification' => 'Not Found',
                'name_of_institution' => 'CMC Institute of Business Management, Skills Training and Assessment Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Aida C. Madulara - President',
                'address' => 'North Poblacion, Larena, Siquijor',
                'latitude_point' => 9.278613093,
                'longitude_point' => 123.584607,
                'tel_no' => '9176710565',
                'e_mail_address' => 'madulara@yahoo.com / cmcsiquijor.skillstraining@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR',
                'sector' => 'Social, Community Development and Other Services',
                'course_registered_program' => 'Bookkeeping NC III',
                'pgf_level' => 'NC III',
                'duration' => '383 Hours',
                'program_reg_no' => '20230761SOCBKP307032',
                'date_issued' => '2023-04-13 00:00:00',
                'expiration_date' => '2028-04-12 00:00:00',
                'trainer' => "Melissa C. Handumon\nJesie B. Dua",
                'nttc' => "NTTC No. 221807121300196\nNTTC No. 222207121300374",
                'expiration_date_of_nttc' => "4/6/2027\n7/20/2027",
            ],
            // Row 8
            [
                'region' => 'VII',
                'province' => 'Siquijor',
                'congressional_district' => 'Lone',
                'municipality' => 'Larena',
                'municipality_class' => '5th',
                'unique_institution_identification' => 'Not Found',
                'name_of_institution' => 'CMC Institute of Business Management, Skills Training and Assessment Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Aida C. Madulara - President',
                'address' => 'North Poblacion, Larena, Siquijor',
                'latitude_point' => 9.278613093,
                'longitude_point' => 123.584607,
                'tel_no' => '9176710565',
                'e_mail_address' => 'madulara@yahoo.com / cmcsiquijor.skillstraining@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR',
                'sector' => 'Tourism',
                'course_registered_program' => 'Tourism Promotion Services NC II',
                'pgf_level' => 'NC II',
                'duration' => '76 Hours',
                'program_reg_no' => '20230761TRSTPS215059',
                'date_issued' => '2023-06-23 00:00:00',
                'expiration_date' => '2028-06-26 00:00:00',
                'trainer' => 'Gemma D. Adovo',
                'nttc' => 'NTTC No. 222207121200400',
                'expiration_date_of_nttc' => 'February 08, 2028',
            ],
            // Row 9
            [
                'region' => 'VII',
                'province' => 'Siquijor',
                'congressional_district' => 'Lone',
                'municipality' => 'Larena',
                'municipality_class' => '5th',
                'unique_institution_identification' => 'Not Found',
                'name_of_institution' => 'CMC Institute of Business Management, Skills Training and Assessment Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Aida C. Madulara - President',
                'address' => 'North Poblacion, Larena, Siquijor',
                'latitude_point' => 9.278613093,
                'longitude_point' => 123.584607,
                'tel_no' => '9176710565',
                'e_mail_address' => 'madulara@yahoo.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR',
                'sector' => 'Electrical and Electronics',
                'course_registered_program' => 'Computer Systems Servicing NC II',
                'pgf_level' => 'NC II',
                'duration' => '360 Hours',
                'program_reg_no' => 'WTR No. 20240761ELCCSS213045',
                'date_issued' => '2024-04-22 00:00:00',
                'expiration_date' => '2024-04-23 00:00:00',
                'trainer' => 'Rex V. Pinton',
                'nttc' => 'NTTC No. 222107611200202',
                'expiration_date_of_nttc' => '04/05/2027',
            ],
            // Row 10 (Newly Added from Image)
            [
                'region' => 'VII',
                'province' => 'Siquijor',
                'congressional_district' => 'Lone',
                'municipality' => 'Lazi',
                'municipality_class' => '4th',
                'unique_institution_identification' => 'Not Found',
                'name_of_institution' => 'PSP Technological Institute Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Pierre S. Pakilit - President',
                'address' => 'Pakilit Residence Alvarico Tigbawan (Pob.) Lazi, Siquijor, Region VII, Philippines 6228',
                'latitude_point' => 9.135146101,
                'longitude_point' => 123.6337518,
                'tel_no' => '0965-774-2490',
                'e_mail_address' => 'psptechnology2019@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR',
                'sector' => 'Construction',
                'course_registered_program' => 'Carpentry NC II',
                'pgf_level' => 'NC II',
                'duration' => '301 Hours',
                'program_reg_no' => 'WTR No. 20240761CONCAR218058',
                'date_issued' => '2024-05-10 00:00:00',
                'expiration_date' => '2029-05-13 00:00:00',
                'trainer' => 'Edward P. Mariño',
                'nttc' => 'NTTC No. 232207461200054',
                'expiration_date_of_nttc' => '18/08/2027',
            ],
            // Row 11 (Previously Row 9 in your code)
            [
                'region' => 'VII',
                'province' => 'Siquijor',
                'congressional_district' => 'Lone',
                'municipality' => 'Larena',
                'municipality_class' => '5th',
                'unique_institution_identification' => 'Not Found',
                'name_of_institution' => 'SBR Technical Education Training Center Inc.',
                'formerly_name_of_tvi' => null,
                'name_of_institution_s_head' => 'Vic Ronald V. Patay, Branch Administrator',
                'address' => 'Basac, Larena, Siquijor',
                'latitude_point' => 9.219327971,
                'longitude_point' => 123.6155831,
                'tel_no' => '0965-145-2942',
                'e_mail_address' => 'sbr.siquijor24@gmail.com',
                'type_of_institution' => 'Private',
                'classification_of_institution' => 'TVI',
                'status' => 'WTR',
                'sector' => 'Construction',
                'course_registered_program' => 'Heavy Equipment Operation (Hydraulic Excavator) NC II',
                'pgf_level' => 'NC II',
                'duration' => '221 hours',
                'program_reg_no' => 'WTR No. 20250761CONHEO219033',
                'date_issued' => '2025-03-19 00:00:00',
                'expiration_date' => '2030-03-20 00:00:00',
                'trainer' => 'Ronie N. Razona',
                'nttc' => 'NTTC No. 232007121200407',
                'expiration_date_of_nttc' => 'July 18, 2028',
            ],

            
        ];

        foreach (array_chunk($rows, 50) as $chunk) {
            DB::table('t_2026_negros_oriental')->insert($chunk);
        }
    }
}